import type { Context, HttpRequest } from '@azure/functions'
import { ScoreDnaRequestSchema } from '../../shared/schemas/dna'
import { getPrincipal, getUserByEmail, requireAdmin, requireAuth } from '../shared/auth'
import { errorResponse, serverError } from '../shared/errors'
import { SCORE_MODEL } from '../shared/dna/models'
import { parseScore } from '../shared/dna/parseScore'
import { scoreDnaPrompt } from '../shared/dna/prompts'
import { callAi } from '../shared/ai/client'

// Generic, stateless quality scoring (spec §9) — assesses any DNA text
// against the rubric. Deliberately has no knowledge of Group/DnaVersion:
// called right after Stage 2 to score the AutoGenerated draft (issue #22),
// and reusable as-is by a later on-demand "Score this DNA" action for any
// version (Imported, Chair-edited) without change.
const httpTrigger = async function (context: Context, req: HttpRequest): Promise<void> {
  const authFailure = requireAuth(req)
  if (authFailure) {
    context.res = authFailure
    return
  }

  const parsed = ScoreDnaRequestSchema.safeParse(req.body)
  if (!parsed.success) {
    context.res = errorResponse(400, 'Invalid request body.', parsed.error.flatten())
    return
  }

  try {
    const principal = getPrincipal(req)!
    const caller = await getUserByEmail(principal.email)
    const roleFailure = requireAdmin(caller)
    if (roleFailure) {
      context.res = roleFailure
      return
    }

    const result = await callAi({
      promptVersion: scoreDnaPrompt,
      messages: [{ role: 'user', content: parsed.data.text }],
      model: SCORE_MODEL,
      maxTokens: 8,
      log: (entry) => context.log(entry),
    })

    const score = parseScore(result.text)
    if (score === null) {
      context.res = errorResponse(502, 'Scoring model did not return a valid 1-5 score.', { raw: result.text })
      return
    }

    context.res = {
      status: 200,
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ score }),
    }
  } catch (err) {
    context.res = serverError(context.log.error, err)
  }
}

module.exports = httpTrigger
