import type { Context, HttpRequest } from '@azure/functions'
import { ImportedSnapshotSchema, ResetGroupRequestSchema, type ResetGroupResponse } from '../../shared/schemas/group'
import { getPrincipal, getUserByEmail, prisma, requireAdmin, requireAuth } from '../shared/auth'
import { errorResponse, serverError } from '../shared/errors'
import { countryForPartnerCode } from '../shared/partnerCodeCountry'

// Admin-only: discard edits made since import and restore the same fields
// Edit can change (name/mmsGroupCode/partnerCode/the 3 profile texts) back
// to Group.importedSnapshot — whatever the group's most recent import/
// re-import actually said. Chair/NA assignment is untouched, same scope as
// Edit itself.
//
// This also fully "unlaunches" the group — lifecycleStatus goes back to
// Imported, approvedFields and pendingReapproval are cleared — since the
// restored text has none of the Generate/Chair-review/Approve progress
// that was made on the text being discarded. getChairGroups/getNaGroups
// both filter to Launched/ChairReview/Approved, so this alone is what
// makes the group actually stop showing up for the Chair/NA — leaving
// lifecycleStatus untouched (the original bug) reverted the text but left
// the group fully visible to both, still showing whatever review/approval
// state it was in.
//
// A new (Imported-stage, unauthored) DnaVersion is created too, snapshotting
// the restored content as the new "latest" — without this, an existing
// AutoGenerated/ChairEdited DnaVersion stays "latest" and getGroup's own
// detail view (which prefers the latest DnaVersion's content over Group's
// own live fields, for previewing an unlaunched draft before Launch) would
// keep showing that stale generated text to the Admin instead of the
// just-restored one.
//
// Reset also clears the group's Network Advisor comments and Chair-AI chat
// history: both are tied to the review round(s) that produced the discarded
// text, and none of it applies to the freshly-restored imported text — left
// in place, they'd resurface as stale/orphaned history the next time the
// group is launched and reviewed. Comments authored by a SalesLeader (an
// enum value with no wired-up feature yet) are left alone; only
// NetworkAdvisor-authored ones are cleared here.
const httpTrigger = async function (context: Context, req: HttpRequest): Promise<void> {
  const authFailure = requireAuth(req)
  if (authFailure) {
    context.res = authFailure
    return
  }

  const parsed = ResetGroupRequestSchema.safeParse(req.body)
  if (!parsed.success) {
    context.res = errorResponse(400, 'Invalid request body.', parsed.error.flatten())
    return
  }

  try {
    const principal = getPrincipal(req)!
    const caller = await getUserByEmail(principal.email)
    const roleFailure = requireAdmin(caller)
    if (roleFailure) {
      context.res = roleFailure
      return
    }

    const { groupId } = parsed.data

    const group = await prisma.group.findUnique({ where: { id: groupId } })
    if (!group) {
      context.res = errorResponse(404, `Group ${groupId} not found.`)
      return
    }

    if (group.importedSnapshot === null) {
      context.res = errorResponse(
        409,
        'This group has no import snapshot to reset to — it was imported before this feature existed. Re-import it to create one.',
      )
      return
    }

    const snapshotParsed = ImportedSnapshotSchema.safeParse(group.importedSnapshot)
    if (!snapshotParsed.success) {
      context.res = errorResponse(500, 'This group’s import snapshot is corrupt and cannot be restored.')
      return
    }
    const snapshot = snapshotParsed.data
    const restoredContent = { groupProfile: snapshot.groupProfile, memberProfile: snapshot.memberProfile, companiesProfile: snapshot.companiesProfile }

    const latest = await prisma.dnaVersion.findFirst({ where: { groupId }, orderBy: { versionNumber: 'desc' } })

    const [updated] = await prisma.$transaction([
      prisma.group.update({
        where: { id: groupId },
        data: {
          name: snapshot.egnGroupName,
          mmsGroupCode: snapshot.mmsGroupCode,
          partnerCode: snapshot.partnerCode,
          country: countryForPartnerCode(snapshot.partnerCode),
          ...restoredContent,
          lifecycleStatus: 'Imported',
          pendingReapproval: false,
          approvedFields: [],
        },
      }),
      prisma.dnaVersion.create({
        data: { groupId, versionNumber: (latest?.versionNumber ?? 0) + 1, content: restoredContent, author: null, scoreStage: 'Imported' },
      }),
      prisma.comment.deleteMany({ where: { groupId, author: 'NetworkAdvisor' } }),
      prisma.aiConversationTurn.deleteMany({ where: { groupId } }),
      prisma.event.create({ data: { groupId, type: 'Reset', actorEmail: principal.email } }),
    ])

    const body: ResetGroupResponse = {
      groupId: updated.id,
      name: updated.name,
      mmsGroupCode: updated.mmsGroupCode,
      partnerCode: updated.partnerCode,
      country: updated.country,
      groupProfile: updated.groupProfile,
      memberProfile: updated.memberProfile,
      companiesProfile: updated.companiesProfile,
      pendingReapproval: updated.pendingReapproval,
    }
    context.res = {
      status: 200,
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(body),
    }
  } catch (err) {
    context.res = serverError(context.log.error, err)
  }
}

module.exports = httpTrigger
