-- CreateEnum
CREATE TYPE "Role" AS ENUM ('Admin', 'Chair', 'NetworkAdvisor', 'ChairLeader', 'SalesLeader');

-- CreateEnum
CREATE TYPE "GroupLifecycleStatus" AS ENUM ('Imported', 'DraftGenerated', 'Launched', 'ChairReview', 'Approved', 'Closed');

-- CreateEnum
CREATE TYPE "DnaField" AS ENUM ('GroupProfile', 'MemberProfile', 'CompaniesProfile');

-- CreateEnum
CREATE TYPE "DnaVersionAuthor" AS ENUM ('Ai', 'Chair', 'Admin', 'NetworkAdvisor');

-- CreateEnum
CREATE TYPE "DnaVersionScoreStage" AS ENUM ('Imported', 'AutoGenerated', 'ChairEdited');

-- CreateEnum
CREATE TYPE "CommentAuthorRole" AS ENUM ('NetworkAdvisor', 'SalesLeader');

-- CreateEnum
CREATE TYPE "EventType" AS ENUM ('Import', 'Generate', 'Launch', 'Reassign', 'Comment', 'Edit', 'Approve', 'Export');

-- CreateEnum
CREATE TYPE "ConversationRole" AS ENUM ('Chair', 'Ai');

-- CreateEnum
CREATE TYPE "ConversationOutcome" AS ENUM ('Accepted', 'Rejected', 'None');

-- CreateTable
CREATE TABLE "User" (
    "email" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "initials" TEXT NOT NULL,
    "roles" "Role"[],
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "User_pkey" PRIMARY KEY ("email")
);

-- CreateTable
CREATE TABLE "Group" (
    "id" TEXT NOT NULL,
    "egnGroupId" TEXT NOT NULL,
    "mmsGroupCode" TEXT,
    "partnerCode" TEXT NOT NULL,
    "country" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "lifecycleStatus" "GroupLifecycleStatus" NOT NULL DEFAULT 'Imported',
    "pendingReapproval" BOOLEAN NOT NULL DEFAULT false,
    "noSourceDna" BOOLEAN NOT NULL DEFAULT false,
    "groupProfile" TEXT NOT NULL,
    "memberProfile" TEXT NOT NULL,
    "companiesProfile" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "chairEmail" TEXT,
    "networkAdvisorEmail" TEXT,

    CONSTRAINT "Group_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "DnaVersion" (
    "id" TEXT NOT NULL,
    "groupId" TEXT NOT NULL,
    "versionNumber" INTEGER NOT NULL,
    "content" JSONB NOT NULL,
    "author" "DnaVersionAuthor" NOT NULL,
    "score" INTEGER,
    "scoreStage" "DnaVersionScoreStage",
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "DnaVersion_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Comment" (
    "id" TEXT NOT NULL,
    "groupId" TEXT NOT NULL,
    "dnaVersionId" TEXT NOT NULL,
    "field" "DnaField" NOT NULL,
    "author" "CommentAuthorRole" NOT NULL,
    "text" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Comment_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Event" (
    "id" TEXT NOT NULL,
    "groupId" TEXT NOT NULL,
    "type" "EventType" NOT NULL,
    "actorEmail" TEXT NOT NULL,
    "timestamp" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Event_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "AiConversationTurn" (
    "id" TEXT NOT NULL,
    "groupId" TEXT NOT NULL,
    "field" "DnaField" NOT NULL,
    "chairEmail" TEXT NOT NULL,
    "role" "ConversationRole" NOT NULL,
    "messageText" TEXT,
    "proposedText" TEXT,
    "outcome" "ConversationOutcome" NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "AiConversationTurn_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "Group_egnGroupId_idx" ON "Group"("egnGroupId");

-- CreateIndex
CREATE UNIQUE INDEX "DnaVersion_groupId_versionNumber_key" ON "DnaVersion"("groupId", "versionNumber");

-- AddForeignKey
ALTER TABLE "Group" ADD CONSTRAINT "Group_chairEmail_fkey" FOREIGN KEY ("chairEmail") REFERENCES "User"("email") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Group" ADD CONSTRAINT "Group_networkAdvisorEmail_fkey" FOREIGN KEY ("networkAdvisorEmail") REFERENCES "User"("email") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "DnaVersion" ADD CONSTRAINT "DnaVersion_groupId_fkey" FOREIGN KEY ("groupId") REFERENCES "Group"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Comment" ADD CONSTRAINT "Comment_groupId_fkey" FOREIGN KEY ("groupId") REFERENCES "Group"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Comment" ADD CONSTRAINT "Comment_dnaVersionId_fkey" FOREIGN KEY ("dnaVersionId") REFERENCES "DnaVersion"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Event" ADD CONSTRAINT "Event_groupId_fkey" FOREIGN KEY ("groupId") REFERENCES "Group"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Event" ADD CONSTRAINT "Event_actorEmail_fkey" FOREIGN KEY ("actorEmail") REFERENCES "User"("email") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "AiConversationTurn" ADD CONSTRAINT "AiConversationTurn_groupId_fkey" FOREIGN KEY ("groupId") REFERENCES "Group"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "AiConversationTurn" ADD CONSTRAINT "AiConversationTurn_chairEmail_fkey" FOREIGN KEY ("chairEmail") REFERENCES "User"("email") ON DELETE RESTRICT ON UPDATE CASCADE;
