import type { Context, HttpRequest } from '@azure/functions'
import { CommitDnaGenerationRequestSchema } from '../../shared/schemas/dna'
import { splitIntoFields } from '../shared/dna/splitFields'
import { getPrincipal, getUserByEmail, prisma, requireAdmin, requireAuth } from '../shared/auth'
import { errorResponse, serverError } from '../shared/errors'

// The non-AI half of "Generate": persists what generateDnaStage1/2 and
// scoreDna already produced. Kept separate from those so no single
// request combines two AI calls (issue #22 — see generateDnaStage1's
// comment for the 45s-cap reasoning); this one makes none.
const httpTrigger = async function (context: Context, req: HttpRequest): Promise<void> {
  const authFailure = requireAuth(req)
  if (authFailure) {
    context.res = authFailure
    return
  }

  const parsed = CommitDnaGenerationRequestSchema.safeParse(req.body)
  if (!parsed.success) {
    context.res = errorResponse(400, 'Invalid request body.', parsed.error.flatten())
    return
  }

  try {
    const principal = getPrincipal(req)!
    const caller = await getUserByEmail(principal.email)
    const roleFailure = requireAdmin(caller)
    if (roleFailure) {
      context.res = roleFailure
      return
    }

    const { groupId, stage2Text, autoGeneratedScore } = parsed.data

    const group = await prisma.group.findUnique({ where: { id: groupId } })
    if (!group) {
      context.res = errorResponse(404, `Group ${groupId} not found.`)
      return
    }

    const lastVersion = await prisma.dnaVersion.findFirst({ where: { groupId }, orderBy: { versionNumber: 'desc' } })

    let importedVersionId: string | null = null
    if (!lastVersion) {
      // First-ever generation for this group: record the original
      // imported text as version 1. score stays null — spec §9 treats it
      // as reference-only, not a launch gate, so it's scored later via a
      // separate on-demand action, not automatically here.
      const imported = await prisma.dnaVersion.create({
        data: {
          groupId,
          versionNumber: 1,
          content: { groupProfile: group.groupProfile, memberProfile: group.memberProfile, companiesProfile: group.companiesProfile },
          author: null,
          scoreStage: 'Imported',
        },
      })
      importedVersionId = imported.id
    }

    const autoGenerated = await prisma.dnaVersion.create({
      data: {
        groupId,
        versionNumber: (lastVersion?.versionNumber ?? 1) + 1,
        content: splitIntoFields(stage2Text),
        author: 'Ai',
        score: autoGeneratedScore,
        scoreStage: 'AutoGenerated',
      },
    })

    if (group.lifecycleStatus === 'Imported') {
      await prisma.group.update({ where: { id: groupId }, data: { lifecycleStatus: 'DraftGenerated' } })
    }

    await prisma.event.create({ data: { groupId, type: 'Generate', actorEmail: principal.email } })

    context.res = {
      status: 200,
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ importedVersionId, autoGeneratedVersionId: autoGenerated.id }),
    }
  } catch (err) {
    context.res = serverError(context.log.error, err)
  }
}

module.exports = httpTrigger
