import { z } from 'zod'

// Matches DnaField/DnaVersion.content's shape — every DNA text, at every
// stage (Imported, AutoGenerated, later Chair-edited), is these 3 fields.
export const DnaContentSchema = z.object({
  groupProfile: z.string(),
  memberProfile: z.string(),
  companiesProfile: z.string(),
})
export type DnaContent = z.infer<typeof DnaContentSchema>

export const GenerateDnaStage1RequestSchema = z.object({
  groupId: z.string().min(1),
})
export const GenerateDnaStage1ResponseSchema = z.object({
  stage1Text: z.string(),
})
export type GenerateDnaStage1Response = z.infer<typeof GenerateDnaStage1ResponseSchema>

export const GenerateDnaStage2RequestSchema = z.object({
  groupId: z.string().min(1),
  stage1Text: z.string().min(1),
  // Optional pasted member roster (titles + companies) — spec §8: grounding
  // context for Stage 2 only, sharpens Member/Companies profile fields.
  roster: z.string().optional(),
})
export const GenerateDnaStage2ResponseSchema = z.object({
  stage2Text: z.string(),
})
export type GenerateDnaStage2Response = z.infer<typeof GenerateDnaStage2ResponseSchema>

export const ScoreDnaRequestSchema = z.object({
  text: z.string().min(1),
})
export const ScoreDnaResponseSchema = z.object({
  score: z.number().int().min(1).max(5),
})
export type ScoreDnaResponse = z.infer<typeof ScoreDnaResponseSchema>

export const CommitDnaGenerationRequestSchema = z.object({
  groupId: z.string().min(1),
  stage2Text: z.string().min(1),
  autoGeneratedScore: z.number().int().min(1).max(5),
})
export const CommitDnaGenerationResponseSchema = z.object({
  // null when the group already had an Imported-stage version (e.g. a regenerate) — nothing new was created for it.
  importedVersionId: z.string().nullable(),
  autoGeneratedVersionId: z.string(),
})
export type CommitDnaGenerationResponse = z.infer<typeof CommitDnaGenerationResponseSchema>
