import 'dotenv/config'
import { PrismaClient } from '@prisma/client'

// Hits a real running Functions host with hand-built x-ms-client-principal
// headers, same local-auth-stub approach as verify-chair-review.ts. Makes
// several real AI calls (chairChat's 800-max-token proposal call,
// suggestImprovements' 500-max-token call) — per the AI call layer's own
// gotcha (CLAUDE_1.md / project memory: "measure real latency before
// trusting the 15s/1-retry default, don't assume it fits"), this script
// logs each call's measured latency so that can be judged from real data.
const databaseUrl = process.env.DATABASE_URL ?? ''
const databaseHost = new URL(databaseUrl).hostname
if (databaseHost !== 'localhost' && databaseHost !== '127.0.0.1') {
  throw new Error(`Refusing to run verify-chair-chat against non-local DATABASE_URL host "${databaseHost}".`)
}

const FUNCTIONS_HOST = process.env.FUNCTIONS_HOST ?? 'http://localhost:7071'
const prisma = new PrismaClient()

function assert(condition: unknown, message: string): asserts condition {
  if (!condition) throw new Error(`Assertion failed: ${message}`)
}

function principalHeader(email: string): string {
  const principal = { userId: email, userDetails: email, identityProvider: 'aad', userRoles: ['authenticated'] }
  return Buffer.from(JSON.stringify(principal), 'utf-8').toString('base64')
}

async function call(path: string, opts: { method: string; email?: string; body?: unknown }) {
  const headers: Record<string, string> = { 'Content-Type': 'application/json' }
  if (opts.email) headers['x-ms-client-principal'] = principalHeader(opts.email)
  const startedAt = Date.now()
  const res = await fetch(`${FUNCTIONS_HOST}${path}`, {
    method: opts.method,
    headers,
    body: opts.body !== undefined ? JSON.stringify(opts.body) : undefined,
  })
  const latencyMs = Date.now() - startedAt
  const json = res.status === 204 ? null : await res.json().catch(() => null)
  return { status: res.status, json, latencyMs }
}

async function main() {
  await prisma.aiConversationTurn.deleteMany({})
  await prisma.comment.deleteMany({})
  await prisma.event.deleteMany({})
  await prisma.dnaVersion.deleteMany({})
  await prisma.group.deleteMany({})
  await prisma.user.deleteMany({})

  const chair1 = 'chair1@example.com'
  const chair2 = 'chair2@example.com' // a different Chair, for ownership scoping
  const naEmail = 'na@example.com'
  await prisma.user.create({ data: { email: chair1, name: 'Chair One', initials: 'C1', roles: ['Chair'] } })
  await prisma.user.create({ data: { email: chair2, name: 'Chair Two', initials: 'C2', roles: ['Chair'] } })
  await prisma.user.create({ data: { email: naEmail, name: 'NA Person', initials: 'NP', roles: ['NetworkAdvisor'] } })

  const groupA = await prisma.group.create({
    data: {
      egnGroupId: 'verify-chat-a',
      partnerCode: 'EGDK',
      country: 'Denmark',
      name: 'Group A (chair1, ChairReview)',
      chairEmail: chair1,
      networkAdvisorEmail: naEmail,
      lifecycleStatus: 'ChairReview',
      groupProfile: 'CEOs of mid-sized companies in Jutland, meeting monthly for peer sparring on growth strategy.',
      memberProfile: 'CEOs with full P&L responsibility, 50-150 employees.',
      companiesProfile: 'Revenue 50-200M DKK, broad industry spread.',
    },
  })
  const dnaVersionA = await prisma.dnaVersion.create({
    data: {
      groupId: groupA.id,
      versionNumber: 1,
      content: { groupProfile: groupA.groupProfile, memberProfile: groupA.memberProfile, companiesProfile: groupA.companiesProfile },
      author: 'Ai',
      scoreStage: 'AutoGenerated',
    },
  })
  await prisma.comment.create({
    data: {
      groupId: groupA.id,
      dnaVersionId: dnaVersionA.id,
      field: 'GroupProfile',
      author: 'NetworkAdvisor',
      text: 'We have historically valued ESG heavily in this group — some members are still with us mainly because of that. Can we mention it briefly?',
    },
  })

  // groupB: chair2's own — chair1 must never reach it via chat/conversation/proposal endpoints.
  const groupB = await prisma.group.create({
    data: {
      egnGroupId: 'verify-chat-b',
      partnerCode: 'EGDK',
      country: 'Denmark',
      name: 'Group B (chair2)',
      chairEmail: chair2,
      lifecycleStatus: 'ChairReview',
      groupProfile: 'GROUP B TEXT',
      memberProfile: 'MEMBER B TEXT',
      companiesProfile: 'COMPANIES B TEXT',
    },
  })
  await prisma.dnaVersion.create({
    data: {
      groupId: groupB.id,
      versionNumber: 1,
      content: { groupProfile: 'GROUP B TEXT', memberProfile: 'MEMBER B TEXT', companiesProfile: 'COMPANIES B TEXT' },
      author: 'Ai',
      scoreStage: 'AutoGenerated',
    },
  })

  // --- 1. Unauthenticated / wrong role.
  let res = await call('/api/chairChat', { method: 'POST', body: { groupId: groupA.id, field: 'GroupProfile', message: 'hi' } })
  assert(res.status === 401, `expected 401 for unauthenticated chairChat, got ${res.status}`)
  res = await call('/api/chairChat', { method: 'POST', email: naEmail, body: { groupId: groupA.id, field: 'GroupProfile', message: 'hi' } })
  assert(res.status === 403, `expected 403 for a non-Chair caller, got ${res.status}`)
  console.log('  1. Auth/role guard (401/403) ok')

  // --- 2. Ownership: chair1 cannot chat on chair2's group.
  res = await call('/api/chairChat', { method: 'POST', email: chair1, body: { groupId: groupB.id, field: 'GroupProfile', message: 'rewrite this' } })
  assert(res.status === 404, `expected 404 for chatting on another Chair's group, got ${res.status}`)
  console.log('  2. Ownership guard (cannot chat on another Chair\'s group) ok')

  // --- 3. Real chat call: a clear instruction to incorporate the NA's comment. Measures latency.
  res = await call('/api/chairChat', {
    method: 'POST',
    email: chair1,
    body: {
      groupId: groupA.id,
      field: 'GroupProfile',
      message: 'Please incorporate the Network Advisor\'s comment about ESG directly into the Group Profile text.',
    },
  })
  assert(res.status === 200, `expected 200 for a real chairChat call, got ${res.status}: ${JSON.stringify(res.json)}`)
  const chatResult = res.json as { clarifyingQuestion: string | null; turnId: string | null; proposedText: string | null; note: string | null }
  console.log(`  3. Real chairChat call latency: ${res.latencyMs}ms (default budget: 15000ms x (1 retry + 1) = 30000ms)`)
  assert(chatResult.clarifyingQuestion === null, `expected a proposal, not a clarifying question, for a clear instruction (got: ${chatResult.clarifyingQuestion})`)
  assert(!!chatResult.turnId && !!chatResult.proposedText, 'a clear instruction produced a proposal with a turnId')
  console.log('  3. Clear instruction produces a real AI proposal (not a clarifying question) ok')

  const turnsAfterChat = await prisma.aiConversationTurn.findMany({ where: { groupId: groupA.id, field: 'GroupProfile' }, orderBy: { createdAt: 'asc' } })
  assert(turnsAfterChat.length === 2, `expected 2 turns (Chair message + Ai reply), got ${turnsAfterChat.length}`)
  assert(turnsAfterChat[0].role === 'Chair' && turnsAfterChat[1].role === 'Ai', 'turns are in Chair-then-Ai order')
  assert(turnsAfterChat[1].proposedText === chatResult.proposedText, "the persisted Ai turn's proposedText matches the response")
  console.log('  4. Both turns persisted, field-scoped, chronological ok')

  // --- 5. Accept the proposal — same save path as editChairField.
  res = await call('/api/acceptChairProposal', { method: 'POST', email: chair1, body: { turnId: chatResult.turnId } })
  assert(res.status === 200, `expected 200 for accepting the proposal, got ${res.status}: ${JSON.stringify(res.json)}`)
  const groupAfterAccept = await prisma.group.findUniqueOrThrow({ where: { id: groupA.id } })
  assert(groupAfterAccept.groupProfile === chatResult.proposedText, "the group's live groupProfile now matches the accepted proposal")
  const acceptedTurn = await prisma.aiConversationTurn.findUniqueOrThrow({ where: { id: chatResult.turnId! } })
  assert(acceptedTurn.outcome === 'Accepted', "the turn's outcome flipped to Accepted")
  const turnsAfterAccept = await prisma.aiConversationTurn.findMany({ where: { groupId: groupA.id, field: 'GroupProfile' } })
  assert(turnsAfterAccept.length === 2, 'accepting a proposal does not add an edit-feedback turn (that guardrail is for manual edits only)')
  console.log('  5. Accept: saved as a Chair edit, no extra edit-feedback turn ok')

  // --- 6. Reject flow: a new proposal on a different field, rejected, must not touch the DB text.
  res = await call('/api/chairChat', {
    method: 'POST',
    email: chair1,
    body: {
      groupId: groupA.id,
      field: 'MemberProfile',
      message: 'Please rewrite this to say "CEOs with full P&L responsibility" without repeating the employee-count range, keeping the same meaning.',
    },
  })
  assert(res.status === 200 && (res.json as { turnId: string | null }).turnId, `expected a proposal for MemberProfile, got ${JSON.stringify(res.json)}`)
  const memberTurnId = (res.json as { turnId: string }).turnId
  res = await call('/api/rejectChairProposal', { method: 'POST', email: chair1, body: { turnId: memberTurnId } })
  assert(res.status === 200, `expected 200 for rejecting a proposal, got ${res.status}`)
  const groupAfterReject = await prisma.group.findUniqueOrThrow({ where: { id: groupA.id } })
  assert(groupAfterReject.memberProfile === 'CEOs with full P&L responsibility, 50-150 employees.', "rejecting a proposal never touched the group's live text")
  const rejectedTurn = await prisma.aiConversationTurn.findUniqueOrThrow({ where: { id: memberTurnId } })
  assert(rejectedTurn.outcome === 'Rejected', "the turn's outcome flipped to Rejected")
  console.log('  6. Reject: outcome recorded, live text untouched ok')

  // --- 7. Accepting/rejecting an already-resolved proposal a second time is rejected, not silently repeated.
  res = await call('/api/acceptChairProposal', { method: 'POST', email: chair1, body: { turnId: memberTurnId } })
  assert(res.status === 400, `expected 400 for accepting an already-rejected proposal, got ${res.status}`)
  console.log('  7. Double-resolving a proposal is rejected ok')

  // --- 8. Clarifying question: nonsense input must never produce a fabricated proposal.
  res = await call('/api/chairChat', { method: 'POST', email: chair1, body: { groupId: groupA.id, field: 'CompaniesProfile', message: 'asdkfj xyz???' } })
  assert(res.status === 200, `expected 200 for the nonsense-input call, got ${res.status}`)
  const nonsenseResult = res.json as { clarifyingQuestion: string | null; turnId: string | null; proposedText: string | null }
  assert(!!nonsenseResult.clarifyingQuestion, `expected a clarifying question for nonsense input, got ${JSON.stringify(nonsenseResult)}`)
  assert(nonsenseResult.turnId === null && nonsenseResult.proposedText === null, 'a clarifying question never carries a turnId or proposedText to act on')
  console.log('  8. Nonsense input produces a clarifying question, never a fabricated proposal ok')

  // --- 9. Conversation history survives the accept — sending a further
  // message on the same field still sees everything from before.
  res = await call('/api/chairChat', {
    method: 'POST',
    email: chair1,
    body: { groupId: groupA.id, field: 'GroupProfile', message: 'Thanks — can you also make the tone a bit more concise?' },
  })
  assert(res.status === 200, `expected 200 for a follow-up chat message, got ${res.status}`)
  res = await call(`/api/getChairFieldConversation?groupId=${groupA.id}&field=GroupProfile`, { method: 'GET', email: chair1 })
  assert(res.status === 200, `expected 200 for getChairFieldConversation, got ${res.status}`)
  const conversation = (res.json as { turns: Array<{ role: string }> }).turns
  assert(conversation.length === 4, `expected all 4 turns (2 from before the accept, 2 new), got ${conversation.length}`)
  console.log('  9. Conversation history survives an accepted edit, unbroken ok')

  // --- 10. Ownership: chair1 cannot read chair2's conversation, or act on chair2's turns.
  res = await call(`/api/getChairFieldConversation?groupId=${groupB.id}&field=GroupProfile`, { method: 'GET', email: chair1 })
  assert(res.status === 404, `expected 404 for reading another Chair's conversation, got ${res.status}`)
  console.log('  10. Ownership guard on conversation read ok')

  // --- 11. suggestImprovements: rejected before the group is fully Approved.
  res = await call('/api/suggestImprovements', { method: 'POST', email: chair1, body: { groupId: groupA.id } })
  assert(res.status === 400, `expected 400 for suggestImprovements before full approval, got ${res.status}`)

  // Approve all 3 fields (reusing issue #25's endpoint) to reach Approved.
  for (const field of ['GroupProfile', 'MemberProfile', 'CompaniesProfile']) {
    res = await call('/api/approveChairField', { method: 'POST', email: chair1, body: { groupId: groupA.id, field } })
    assert(res.status === 200, `expected 200 approving ${field}, got ${res.status}`)
  }
  const groupAfterApproval = await prisma.group.findUniqueOrThrow({ where: { id: groupA.id } })
  assert(groupAfterApproval.lifecycleStatus === 'Approved', 'group is now Approved')

  res = await call('/api/suggestImprovements', { method: 'POST', email: chair1, body: { groupId: groupA.id } })
  assert(res.status === 200, `expected 200 for suggestImprovements once Approved, got ${res.status}: ${JSON.stringify(res.json)}`)
  console.log(`  11. suggestImprovements real call latency: ${res.latencyMs}ms`)
  const suggestions = (res.json as { suggestions: Array<{ field: string; suggestion: string } > }).suggestions
  assert(Array.isArray(suggestions), 'suggestions is an array (possibly empty — that is a valid, honest answer)')
  for (const s of suggestions) {
    assert(['GroupProfile', 'MemberProfile', 'CompaniesProfile'].includes(s.field), `suggestion field "${s.field}" is a real DnaField value`)
  }
  console.log(`  11. suggestImprovements gated on Approved, returns ${suggestions.length} well-formed suggestion(s) ok`)

  console.log('verify-chair-chat: all checks passed')
}

main()
  .catch((err) => {
    console.error(err)
    process.exitCode = 1
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
