import 'dotenv/config'
import { PrismaClient } from '@prisma/client'

// Hits a real running Functions host with hand-built x-ms-client-principal
// headers, same local-auth-stub approach as verify-na-comments.ts. Makes a
// real AI call for editChairField's post-edit feedback (cheap, small maxTokens).
const databaseUrl = process.env.DATABASE_URL ?? ''
const databaseHost = new URL(databaseUrl).hostname
if (databaseHost !== 'localhost' && databaseHost !== '127.0.0.1') {
  throw new Error(`Refusing to run verify-chair-review against non-local DATABASE_URL host "${databaseHost}".`)
}

const FUNCTIONS_HOST = process.env.FUNCTIONS_HOST ?? 'http://localhost:7071'
const prisma = new PrismaClient()

function assert(condition: unknown, message: string): asserts condition {
  if (!condition) throw new Error(`Assertion failed: ${message}`)
}

function principalHeader(email: string): string {
  const principal = { userId: email, userDetails: email, identityProvider: 'aad', userRoles: ['authenticated'] }
  return Buffer.from(JSON.stringify(principal), 'utf-8').toString('base64')
}

async function call(path: string, opts: { method: string; email?: string; body?: unknown }) {
  const headers: Record<string, string> = { 'Content-Type': 'application/json' }
  if (opts.email) headers['x-ms-client-principal'] = principalHeader(opts.email)
  const res = await fetch(`${FUNCTIONS_HOST}${path}`, {
    method: opts.method,
    headers,
    body: opts.body !== undefined ? JSON.stringify(opts.body) : undefined,
  })
  const json = res.status === 204 ? null : await res.json().catch(() => null)
  return { status: res.status, json }
}

async function main() {
  await prisma.aiConversationTurn.deleteMany({})
  await prisma.comment.deleteMany({})
  await prisma.event.deleteMany({})
  await prisma.dnaVersion.deleteMany({})
  await prisma.group.deleteMany({})
  await prisma.user.deleteMany({})

  const chair1 = 'chair1@example.com'
  const chair2 = 'chair2@example.com' // a different Chair, for the ownership-scoping check
  const naEmail = 'na@example.com'
  await prisma.user.create({ data: { email: chair1, name: 'Chair One', initials: 'C1', roles: ['Chair'] } })
  await prisma.user.create({ data: { email: chair2, name: 'Chair Two', initials: 'C2', roles: ['Chair'] } })
  await prisma.user.create({ data: { email: naEmail, name: 'NA Person', initials: 'NP', roles: ['NetworkAdvisor'] } })

  // groupA: chair1's own, in ChairReview, with an unresolved NA comment on GroupProfile.
  const groupA = await prisma.group.create({
    data: {
      egnGroupId: 'verify-chair-a',
      partnerCode: 'EGDK',
      country: 'Denmark',
      name: 'Group A (chair1, ChairReview)',
      chairEmail: chair1,
      networkAdvisorEmail: naEmail,
      lifecycleStatus: 'ChairReview',
      groupProfile: 'GROUP A TEXT',
      memberProfile: 'MEMBER A TEXT',
      companiesProfile: 'COMPANIES A TEXT',
    },
  })
  const dnaVersionA = await prisma.dnaVersion.create({
    data: {
      groupId: groupA.id,
      versionNumber: 1,
      content: { groupProfile: 'GROUP A TEXT', memberProfile: 'MEMBER A TEXT', companiesProfile: 'COMPANIES A TEXT' },
      author: 'Ai',
      scoreStage: 'AutoGenerated',
      score: 4,
    },
  })
  const comment = await prisma.comment.create({
    data: {
      groupId: groupA.id,
      dnaVersionId: dnaVersionA.id,
      field: 'GroupProfile',
      author: 'NetworkAdvisor',
      text: 'Please double-check this still matches what we tell prospects.',
    },
  })

  // groupB: chair2's own — chair1 must never see or write to this one.
  const groupB = await prisma.group.create({
    data: {
      egnGroupId: 'verify-chair-b',
      partnerCode: 'EGDK',
      country: 'Denmark',
      name: 'Group B (chair2, ChairReview)',
      chairEmail: chair2,
      lifecycleStatus: 'ChairReview',
      groupProfile: 'GROUP B TEXT',
      memberProfile: 'MEMBER B TEXT',
      companiesProfile: 'COMPANIES B TEXT',
    },
  })
  await prisma.dnaVersion.create({
    data: {
      groupId: groupB.id,
      versionNumber: 1,
      content: { groupProfile: 'GROUP B TEXT', memberProfile: 'MEMBER B TEXT', companiesProfile: 'COMPANIES B TEXT' },
      author: 'Ai',
      scoreStage: 'AutoGenerated',
    },
  })

  // --- 1. Unauthenticated / wrong role.
  let res = await call('/api/getChairGroups', { method: 'GET' })
  assert(res.status === 401, `expected 401 for unauthenticated getChairGroups, got ${res.status}`)
  res = await call('/api/getChairGroups', { method: 'GET', email: naEmail })
  assert(res.status === 403, `expected 403 for a non-Chair caller, got ${res.status}`)
  console.log('  1. Auth/role guard (401/403) ok')

  // --- 2. List view: chair1 sees only their own group.
  res = await call('/api/getChairGroups', { method: 'GET', email: chair1 })
  assert(res.status === 200, `expected 200 for chair1's list, got ${res.status}`)
  const list = (res.json as { groups: Array<{ id: string }> }).groups
  assert(list.length === 1 && list[0].id === groupA.id, "chair1's list contains only groupA")
  assert(!JSON.stringify(list).toLowerCase().includes('score'), 'no "score" field leaks in the list response')
  console.log('  2. List view ownership scoping + no score leak ok')

  // --- 3. Ownership guard on detail + actions: chair1 cannot read/write groupB.
  res = await call(`/api/getChairGroup?groupId=${groupB.id}`, { method: 'GET', email: chair1 })
  assert(res.status === 404, `expected 404 for chair1 reading chair2's group, got ${res.status}`)
  res = await call('/api/approveChairField', { method: 'POST', email: chair1, body: { groupId: groupB.id, field: 'GroupProfile' } })
  assert(res.status === 404, `expected 404 for chair1 approving a field on chair2's group, got ${res.status}`)
  console.log('  3. Ownership guard (cannot read/write another Chair\'s group) ok')

  // --- 4. Detail view: shows the group's fields, current text, and the unresolved NA comment. No score.
  res = await call(`/api/getChairGroup?groupId=${groupA.id}`, { method: 'GET', email: chair1 })
  assert(res.status === 200, `expected 200 for chair1's own group detail, got ${res.status}`)
  const detail = res.json as { fields: Array<{ field: string; text: string; approved: boolean; unresolvedComments: Array<{ text: string }> }> }
  const groupProfileField = detail.fields.find((f) => f.field === 'GroupProfile')!
  assert(groupProfileField.unresolvedComments.length === 1, 'GroupProfile field shows the unresolved NA comment')
  assert(!groupProfileField.approved, 'GroupProfile starts unapproved')
  assert(!JSON.stringify(detail).toLowerCase().includes('score'), 'no "score" field leaks in the detail response')
  console.log('  4. Detail view ok: fields, unresolved comment, no score leak')

  // --- 5. "Read & accept": approve GroupProfile as-is — resolves the NA comment too.
  res = await call('/api/approveChairField', { method: 'POST', email: chair1, body: { groupId: groupA.id, field: 'GroupProfile' } })
  assert(res.status === 200, `expected 200 for approving GroupProfile, got ${res.status}`)
  assert((res.json as { justFullyApproved: boolean }).justFullyApproved === false, 'not fully approved yet — 2 fields remain')
  const commentAfterAccept = await prisma.comment.findUniqueOrThrow({ where: { id: comment.id } })
  assert(commentAfterAccept.resolved, "Read & accept resolved the NA's comment")
  console.log('  5. Read & accept: field approved, NA comment resolved ok')

  // --- 6. Manual edit path: rewrite MemberProfile — versions it, updates the group's live text,
  // and asks the AI for feedback (real call), posted as an AiConversationTurn.
  res = await call('/api/editChairField', {
    method: 'POST',
    email: chair1,
    body: { groupId: groupA.id, field: 'MemberProfile', text: 'REWRITTEN MEMBER A TEXT — CEOs of mid-sized companies, 50-150 employees.' },
  })
  assert(res.status === 200, `expected 200 for editing MemberProfile, got ${res.status}: ${JSON.stringify(res.json)}`)
  const editResult = res.json as { dnaVersionId: string; aiFeedback: string }
  assert(editResult.aiFeedback.length > 0, 'editChairField returned non-empty AI feedback')

  const groupAfterEdit = await prisma.group.findUniqueOrThrow({ where: { id: groupA.id } })
  assert(groupAfterEdit.memberProfile.startsWith('REWRITTEN MEMBER A TEXT'), "group's live memberProfile was updated")
  const versionAfterEdit = await prisma.dnaVersion.findUniqueOrThrow({ where: { id: editResult.dnaVersionId } })
  assert(versionAfterEdit.versionNumber === 2, 'a new DnaVersion (v2) was created for the edit')
  assert(versionAfterEdit.author === 'Chair' && versionAfterEdit.scoreStage === 'ChairEdited' && versionAfterEdit.score === null, 'new version is Chair-authored, ChairEdited stage, unscored')
  const contentAfterEdit = versionAfterEdit.content as { groupProfile: string; memberProfile: string; companiesProfile: string }
  assert(contentAfterEdit.groupProfile === 'GROUP A TEXT', 'the new version kept the unrelated GroupProfile text unchanged')

  const turns = await prisma.aiConversationTurn.findMany({ where: { groupId: groupA.id, field: 'MemberProfile' } })
  assert(turns.length === 1 && turns[0].role === 'Ai' && turns[0].messageText === editResult.aiFeedback, "the AI's feedback was posted into that field's conversation")
  console.log('  6. Manual edit: versioned, group text updated, real AI feedback posted to conversation ok')

  // --- 7. Approve the remaining 2 fields — the 3rd approval flips the group to Approved.
  res = await call('/api/approveChairField', { method: 'POST', email: chair1, body: { groupId: groupA.id, field: 'MemberProfile' } })
  assert(res.status === 200 && (res.json as { justFullyApproved: boolean }).justFullyApproved === false, 'still not fully approved — 1 field remains')
  res = await call('/api/approveChairField', { method: 'POST', email: chair1, body: { groupId: groupA.id, field: 'CompaniesProfile' } })
  assert(res.status === 200, `expected 200 for the final field approval, got ${res.status}`)
  assert((res.json as { justFullyApproved: boolean; lifecycleStatus: string }).justFullyApproved === true, 'approving the 3rd field reports justFullyApproved')
  assert((res.json as { lifecycleStatus: string }).lifecycleStatus === 'Approved', 'response reports Approved status')

  const groupAfterApproval = await prisma.group.findUniqueOrThrow({ where: { id: groupA.id } })
  assert(groupAfterApproval.lifecycleStatus === 'Approved', "group's lifecycleStatus flipped to Approved")
  const approveEvents = await prisma.event.findMany({ where: { groupId: groupA.id, type: 'Approve' } })
  assert(approveEvents.length === 1, 'an Approve event was logged for the full approval')
  console.log('  7. Full approval (3rd field) flips group to Approved, event logged ok')

  // --- 8. Editing a field on an already-Approved group sets pendingReapproval, not a new status.
  res = await call('/api/editChairField', {
    method: 'POST',
    email: chair1,
    body: { groupId: groupA.id, field: 'CompaniesProfile', text: 'REWRITTEN COMPANIES A TEXT after approval.' },
  })
  assert(res.status === 200, `expected 200 for a post-approval edit, got ${res.status}`)
  const groupAfterPostApprovalEdit = await prisma.group.findUniqueOrThrow({ where: { id: groupA.id } })
  assert(groupAfterPostApprovalEdit.lifecycleStatus === 'Approved', 'lifecycleStatus stays Approved after a post-approval edit — no separate status')
  assert(groupAfterPostApprovalEdit.pendingReapproval === true, 'pendingReapproval is set instead')
  assert(groupAfterPostApprovalEdit.approvedFields.includes('CompaniesProfile'), 'the edited field is still marked approved — an edit never un-approves it')
  console.log('  8. Post-approval edit: status stays Approved, pendingReapproval set, field stays approved ok')

  // --- 9. "Approve whole DNA" (reapprove): clears pendingReapproval, no blocking modal, logs another Approve event.
  res = await call('/api/reapproveChairGroup', { method: 'POST', email: chair1, body: { groupId: groupA.id } })
  assert(res.status === 200, `expected 200 for reapproveChairGroup, got ${res.status}: ${JSON.stringify(res.json)}`)
  assert((res.json as { pendingReapproval: boolean }).pendingReapproval === false, 'response reports pendingReapproval cleared')
  const groupAfterReapprove = await prisma.group.findUniqueOrThrow({ where: { id: groupA.id } })
  assert(groupAfterReapprove.pendingReapproval === false, "group's pendingReapproval cleared in the DB")
  const approveEventsAfterReapprove = await prisma.event.findMany({ where: { groupId: groupA.id, type: 'Approve' } })
  assert(approveEventsAfterReapprove.length === 2, 'a second Approve event was logged for the re-approval')

  // Reapproving again with nothing pending is rejected, not silently accepted.
  res = await call('/api/reapproveChairGroup', { method: 'POST', email: chair1, body: { groupId: groupA.id } })
  assert(res.status === 400, `expected 400 for reapproving with nothing pending, got ${res.status}`)
  console.log('  9. Reapprove: clears the flag, logs an event, rejects when nothing is pending ok')

  console.log('verify-chair-review: all checks passed')
}

main()
  .catch((err) => {
    console.error(err)
    process.exitCode = 1
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
