import 'dotenv/config'
import { PrismaClient } from '@prisma/client'

// Hits a real running Functions host with hand-built x-ms-client-principal
// headers, same local-auth-stub approach as verify-groups-import.ts. No AI
// calls in this ticket — launchGroup is a pure DB action, and the
// checkGroupImport fix is pure comparison logic — so this is fast and free
// to run.
const databaseUrl = process.env.DATABASE_URL ?? ''
const databaseHost = new URL(databaseUrl).hostname
if (databaseHost !== 'localhost' && databaseHost !== '127.0.0.1') {
  throw new Error(`Refusing to run verify-launch against non-local DATABASE_URL host "${databaseHost}".`)
}

const FUNCTIONS_HOST = process.env.FUNCTIONS_HOST ?? 'http://localhost:7071'
const prisma = new PrismaClient()

function assert(condition: unknown, message: string): asserts condition {
  if (!condition) throw new Error(`Assertion failed: ${message}`)
}

function principalHeader(email: string): string {
  const principal = { userId: email, userDetails: email, identityProvider: 'aad', userRoles: ['authenticated'] }
  return Buffer.from(JSON.stringify(principal), 'utf-8').toString('base64')
}

async function call(path: string, opts: { method: string; email?: string; body?: unknown }) {
  const headers: Record<string, string> = { 'Content-Type': 'application/json' }
  if (opts.email) headers['x-ms-client-principal'] = principalHeader(opts.email)
  const res = await fetch(`${FUNCTIONS_HOST}${path}`, {
    method: opts.method,
    headers,
    body: opts.body ? JSON.stringify(opts.body) : undefined,
  })
  const json = res.status === 204 ? null : await res.json().catch(() => null)
  return { status: res.status, json }
}

function rawRow(overrides: Partial<Record<string, string>> = {}) {
  return {
    egnGroupName: 'Verify Launch Group',
    egnGroupId: 'verify-launch-1',
    mmsGroupCode: '02092-EGDK',
    partnerCode: 'EGDK',
    groupProfile: 'ORIGINAL TEXT A',
    memberProfile: 'ORIGINAL MEMBER A',
    companiesProfile: 'ORIGINAL COMPANIES A',
    responsibleChairName: 'Chair Person',
    responsibleSalesName: 'NA Person',
    ...overrides,
  }
}

async function main() {
  await prisma.comment.deleteMany({})
  await prisma.event.deleteMany({})
  await prisma.dnaVersion.deleteMany({})
  await prisma.group.deleteMany({})
  await prisma.user.deleteMany({})

  const adminEmail = 'admin@example.com'
  await prisma.user.create({ data: { email: adminEmail, name: 'Admin', initials: 'AD', roles: ['Admin'] } })

  // --- Scenario A: first launch.
  const group = await prisma.group.create({
    data: {
      egnGroupId: 'verify-launch-1',
      partnerCode: 'EGDK',
      country: 'Denmark',
      name: 'Verify Launch Group',
      lifecycleStatus: 'DraftGenerated',
      groupProfile: 'ORIGINAL TEXT A',
      memberProfile: 'ORIGINAL MEMBER A',
      companiesProfile: 'ORIGINAL COMPANIES A',
    },
  })
  await prisma.dnaVersion.create({
    data: {
      groupId: group.id,
      versionNumber: 1,
      content: { groupProfile: 'ORIGINAL TEXT A', memberProfile: 'ORIGINAL MEMBER A', companiesProfile: 'ORIGINAL COMPANIES A' },
      author: null,
      scoreStage: 'Imported',
    },
  })
  await prisma.dnaVersion.create({
    data: {
      groupId: group.id,
      versionNumber: 2,
      content: { groupProfile: 'REWRITTEN TEXT A', memberProfile: 'REWRITTEN MEMBER A', companiesProfile: 'REWRITTEN COMPANIES A' },
      author: 'Ai',
      score: 4,
      scoreStage: 'AutoGenerated',
    },
  })

  const launched = await call('/api/launchGroup', { method: 'POST', email: adminEmail, body: { groupId: group.id } })
  assert(launched.status === 200, `launchGroup succeeded (got ${launched.status}: ${JSON.stringify(launched.json)})`)
  assert(launched.json.lifecycleStatus === 'Launched', 'response reports Launched status')
  assert(launched.json.launchedVersionNumber === 2, 'response reports the version number that was launched')

  const groupAfterLaunch = await prisma.group.findUniqueOrThrow({ where: { id: group.id } })
  assert(groupAfterLaunch.lifecycleStatus === 'Launched', 'Group.lifecycleStatus flipped to Launched')
  assert(groupAfterLaunch.groupProfile === 'REWRITTEN TEXT A', "Group's profile fields were copied from the AI draft")
  assert(groupAfterLaunch.memberProfile === 'REWRITTEN MEMBER A', "Group's member field was copied from the AI draft")

  const launchEvents = await prisma.event.findMany({ where: { groupId: group.id, type: 'Launch' } })
  assert(launchEvents.length === 1, 'a Launch event was logged')

  console.log('  Scenario A (first launch) ok: status=Launched, fields copied from the AI draft, event logged')

  // --- Scenario B: the regression this ticket fixes. Re-importing the
  // group's TRUE original text (unchanged in Salesforce) must still read
  // as "unchanged", even though Group's own fields now hold the launched,
  // AI-rewritten text.
  const unchangedCheck = await call('/api/checkGroupImport', { method: 'POST', email: adminEmail, body: { rows: [rawRow()] } })
  assert(unchangedCheck.status === 200, `checkGroupImport succeeded (got ${unchangedCheck.status})`)
  assert(unchangedCheck.json[0].status === 'unchanged', `re-importing the true original reads as unchanged, not clobbered by the launched text (got "${unchangedCheck.json[0].status}")`)

  const changedCheck = await call('/api/checkGroupImport', {
    method: 'POST',
    email: adminEmail,
    body: { rows: [rawRow({ groupProfile: 'A GENUINELY DIFFERENT ORIGINAL TEXT' })] },
  })
  assert(changedCheck.json[0].status === 'changed', 'a genuinely different re-import still reads as changed')

  console.log('  Scenario B (re-import after launch) ok: compares against the true original, not the launched text')

  // --- Scenario C: relaunch after a later regenerate, from Approved status.
  await prisma.group.update({ where: { id: group.id }, data: { lifecycleStatus: 'Approved', pendingReapproval: true } })
  await prisma.dnaVersion.create({
    data: {
      groupId: group.id,
      versionNumber: 3,
      content: { groupProfile: 'REWRITTEN TEXT A v2', memberProfile: 'REWRITTEN MEMBER A v2', companiesProfile: 'REWRITTEN COMPANIES A v2' },
      author: 'Ai',
      score: 5,
      scoreStage: 'AutoGenerated',
    },
  })

  const relaunched = await call('/api/launchGroup', { method: 'POST', email: adminEmail, body: { groupId: group.id } })
  assert(relaunched.status === 200, `relaunch succeeded (got ${relaunched.status}: ${JSON.stringify(relaunched.json)})`)
  assert(relaunched.json.launchedVersionNumber === 3, 'relaunch pushed the newest (v3) draft, not an older one')

  const groupAfterRelaunch = await prisma.group.findUniqueOrThrow({ where: { id: group.id } })
  assert(groupAfterRelaunch.lifecycleStatus === 'Launched', 'relaunch flips status back to Launched from Approved')
  assert(groupAfterRelaunch.groupProfile === 'REWRITTEN TEXT A v2', 'relaunch copied the newest draft, not the original launch')
  assert(groupAfterRelaunch.pendingReapproval === false, 'relaunch clears any pending-reapproval flag from before')

  const launchEventsAfterRelaunch = await prisma.event.findMany({ where: { groupId: group.id, type: 'Launch' } })
  assert(launchEventsAfterRelaunch.length === 2, 'a second Launch event was logged for the relaunch')

  console.log('  Scenario C (relaunch from Approved) ok: pushed the newest draft, cleared pending-reapproval, logged a second event')

  // --- Scenario D: guards.
  const closedGroup = await prisma.group.create({
    data: {
      egnGroupId: 'verify-launch-closed',
      partnerCode: 'EGDK',
      country: 'Denmark',
      name: 'Verify Launch — closed group',
      lifecycleStatus: 'Closed',
      groupProfile: 'x',
      memberProfile: '',
      companiesProfile: '',
    },
  })
  const closedAttempt = await call('/api/launchGroup', { method: 'POST', email: adminEmail, body: { groupId: closedGroup.id } })
  assert(closedAttempt.status === 400, `launching a Closed group is rejected (got ${closedAttempt.status})`)

  const noDraftGroup = await prisma.group.create({
    data: {
      egnGroupId: 'verify-launch-no-draft',
      partnerCode: 'EGDK',
      country: 'Denmark',
      name: 'Verify Launch — no draft yet',
      groupProfile: 'x',
      memberProfile: '',
      companiesProfile: '',
    },
  })
  const noDraftAttempt = await call('/api/launchGroup', { method: 'POST', email: adminEmail, body: { groupId: noDraftGroup.id } })
  assert(noDraftAttempt.status === 400, `launching a group with no AI draft yet is rejected (got ${noDraftAttempt.status})`)

  console.log('  Scenario D (guards) ok: Closed group and no-pending-draft group both rejected')
  console.log('verify-launch: all checks passed')
}

main()
  .catch((err) => {
    console.error(err)
    process.exit(1)
  })
  .finally(() => prisma.$disconnect())
