import 'dotenv/config'
import { PrismaClient } from '@prisma/client'

// Hits a real running Functions host with hand-built x-ms-client-principal
// headers, same local-auth-stub approach as verify-launch.ts/verify-users-auth.ts.
const databaseUrl = process.env.DATABASE_URL ?? ''
const databaseHost = new URL(databaseUrl).hostname
if (databaseHost !== 'localhost' && databaseHost !== '127.0.0.1') {
  throw new Error(`Refusing to run verify-na-comments against non-local DATABASE_URL host "${databaseHost}".`)
}

const FUNCTIONS_HOST = process.env.FUNCTIONS_HOST ?? 'http://localhost:7071'
const prisma = new PrismaClient()

function assert(condition: unknown, message: string): asserts condition {
  if (!condition) throw new Error(`Assertion failed: ${message}`)
}

function principalHeader(email: string): string {
  const principal = { userId: email, userDetails: email, identityProvider: 'aad', userRoles: ['authenticated'] }
  return Buffer.from(JSON.stringify(principal), 'utf-8').toString('base64')
}

async function call(path: string, opts: { method: string; email?: string; body?: unknown }) {
  const headers: Record<string, string> = { 'Content-Type': 'application/json' }
  if (opts.email) headers['x-ms-client-principal'] = principalHeader(opts.email)
  const res = await fetch(`${FUNCTIONS_HOST}${path}`, {
    method: opts.method,
    headers,
    body: opts.body !== undefined ? JSON.stringify(opts.body) : undefined,
  })
  const json = res.status === 204 ? null : await res.json().catch(() => null)
  return { status: res.status, json }
}

async function main() {
  await prisma.aiConversationTurn.deleteMany({})
  await prisma.comment.deleteMany({})
  await prisma.event.deleteMany({})
  await prisma.dnaVersion.deleteMany({})
  await prisma.group.deleteMany({})
  await prisma.user.deleteMany({})

  const chairEmail = 'chair@example.com'
  const na1 = 'na1@example.com'
  const na2 = 'na2@example.com' // a different Network Advisor, for the ownership-scoping check
  await prisma.user.create({ data: { email: chairEmail, name: 'Chair Person', initials: 'CP', roles: ['Chair'] } })
  await prisma.user.create({ data: { email: na1, name: 'NA One', initials: 'N1', roles: ['NetworkAdvisor'] } })
  await prisma.user.create({ data: { email: na2, name: 'NA Two', initials: 'N2', roles: ['NetworkAdvisor'] } })

  // groupA: na1's own, Launched — the one na1 should be able to comment on.
  const groupA = await prisma.group.create({
    data: {
      egnGroupId: 'verify-na-a',
      partnerCode: 'EGDK',
      country: 'Denmark',
      name: 'Group A (na1, Launched)',
      chairEmail,
      networkAdvisorEmail: na1,
      lifecycleStatus: 'Launched',
      groupProfile: 'GROUP A TEXT',
      memberProfile: 'MEMBER A TEXT',
      companiesProfile: 'COMPANIES A TEXT',
    },
  })
  const dnaVersionA = await prisma.dnaVersion.create({
    data: {
      groupId: groupA.id,
      versionNumber: 1,
      content: { groupProfile: 'GROUP A TEXT', memberProfile: 'MEMBER A TEXT', companiesProfile: 'COMPANIES A TEXT' },
      author: 'Ai',
      score: 5,
      scoreStage: 'AutoGenerated',
    },
  })

  // groupB: na2's own, Launched — na1 must never see or write to this one.
  const groupB = await prisma.group.create({
    data: {
      egnGroupId: 'verify-na-b',
      partnerCode: 'EGDK',
      country: 'Denmark',
      name: 'Group B (na2, Launched)',
      networkAdvisorEmail: na2,
      lifecycleStatus: 'Launched',
      groupProfile: 'GROUP B TEXT',
      memberProfile: 'MEMBER B TEXT',
      companiesProfile: 'COMPANIES B TEXT',
    },
  })
  await prisma.dnaVersion.create({
    data: {
      groupId: groupB.id,
      versionNumber: 1,
      content: { groupProfile: 'GROUP B TEXT', memberProfile: 'MEMBER B TEXT', companiesProfile: 'COMPANIES B TEXT' },
      author: 'Ai',
      scoreStage: 'AutoGenerated',
    },
  })

  // groupC: na1's own, but not yet Launched — must not appear in the list,
  // and a direct write attempt must be rejected by status, not silently allowed.
  const groupC = await prisma.group.create({
    data: {
      egnGroupId: 'verify-na-c',
      partnerCode: 'EGDK',
      country: 'Denmark',
      name: 'Group C (na1, DraftGenerated)',
      networkAdvisorEmail: na1,
      lifecycleStatus: 'DraftGenerated',
      groupProfile: 'GROUP C TEXT',
      memberProfile: '',
      companiesProfile: '',
    },
  })

  // --- 1. Unauthenticated: 401 on every endpoint.
  let res = await call('/api/getNaGroups', { method: 'GET' })
  assert(res.status === 401, `expected 401 for unauthenticated getNaGroups, got ${res.status}`)
  res = await call('/api/putNaComments', { method: 'POST', body: { groupId: groupA.id, comments: [{ field: 'GroupProfile', text: 'x' }] } })
  assert(res.status === 401, `expected 401 for unauthenticated putNaComments, got ${res.status}`)
  res = await call('/api/dismissNaGuidance', { method: 'POST' })
  assert(res.status === 401, `expected 401 for unauthenticated dismissNaGuidance, got ${res.status}`)
  console.log('  1. Unauthenticated calls rejected (401) ok')

  // --- 2. Authenticated but not a Network Advisor: 403 on every endpoint.
  res = await call('/api/getNaGroups', { method: 'GET', email: chairEmail })
  assert(res.status === 403, `expected 403 for non-NA getNaGroups, got ${res.status}`)
  res = await call('/api/putNaComments', {
    method: 'POST',
    email: chairEmail,
    body: { groupId: groupA.id, comments: [{ field: 'GroupProfile', text: 'x' }] },
  })
  assert(res.status === 403, `expected 403 for non-NA putNaComments, got ${res.status}`)
  res = await call('/api/dismissNaGuidance', { method: 'POST', email: chairEmail })
  assert(res.status === 403, `expected 403 for non-NA dismissNaGuidance, got ${res.status}`)
  console.log('  2. Non-Network-Advisor calls rejected (403) ok')

  // --- 3. na1 sees only their own Launched group (not na2's, not their own
  // not-yet-Launched one), the first-time guidance flag is true, and no
  // score data leaks anywhere in the response.
  res = await call('/api/getNaGroups', { method: 'GET', email: na1 })
  assert(res.status === 200, `expected 200 for na1 getNaGroups, got ${res.status}`)
  const firstLoad = res.json as { groups: Array<{ id: string }>; showGuidance: boolean }
  assert(firstLoad.groups.length === 1, `expected exactly 1 group for na1, got ${firstLoad.groups.length}`)
  assert(firstLoad.groups[0].id === groupA.id, "na1's list contains groupA")
  assert(firstLoad.showGuidance === true, 'showGuidance is true before the banner has ever been dismissed')
  assert(!JSON.stringify(firstLoad).includes('score'), 'no "score" field leaks anywhere in the NA groups response')
  console.log('  3. Ownership + status scoping, first-time guidance flag, no score leak ok')

  // --- 4. Dismissing guidance persists across a later call.
  res = await call('/api/dismissNaGuidance', { method: 'POST', email: na1 })
  assert(res.status === 200, `expected 200 for dismissNaGuidance, got ${res.status}`)
  res = await call('/api/getNaGroups', { method: 'GET', email: na1 })
  assert((res.json as { showGuidance: boolean }).showGuidance === false, 'showGuidance is false after dismissing, on a later call')
  console.log('  4. Guidance-seen flag persists server-side ok')

  // --- 5. Ownership guard: na1 cannot comment on na2's group.
  res = await call('/api/putNaComments', {
    method: 'POST',
    email: na1,
    body: { groupId: groupB.id, comments: [{ field: 'GroupProfile', text: 'not mine to comment on' }] },
  })
  assert(res.status === 404, `expected 404 for commenting on another NA's group, got ${res.status}`)
  assert((await prisma.comment.count({ where: { groupId: groupB.id } })) === 0, 'no Comment row created for groupB')
  console.log('  5. Ownership guard (cannot write to another NA\'s group) ok')

  // --- 6. Status guard: na1's own group, but not Launched yet.
  res = await call('/api/putNaComments', {
    method: 'POST',
    email: na1,
    body: { groupId: groupC.id, comments: [{ field: 'GroupProfile', text: 'too early' }] },
  })
  assert(res.status === 400, `expected 400 for commenting on a not-yet-Launched group, got ${res.status}`)
  console.log('  6. Status guard (must be Launched) ok')

  // --- 7. Validation: at least one comment required.
  res = await call('/api/putNaComments', { method: 'POST', email: na1, body: { groupId: groupA.id, comments: [] } })
  assert(res.status === 400, `expected 400 for an empty comments array, got ${res.status}`)
  console.log('  7. Empty-comments validation ok')

  // --- 8. The real "Send to Chair" action: writes real Comment rows against
  // the current DnaVersion, and moves the group to ChairReview.
  res = await call('/api/putNaComments', {
    method: 'POST',
    email: na1,
    body: {
      groupId: groupA.id,
      comments: [
        { field: 'GroupProfile', text: 'check this still matches what we tell prospects' },
        { field: 'MemberProfile', text: 'membership count looks off' },
      ],
    },
  })
  assert(res.status === 200, `expected 200 for a valid Send to Chair, got ${res.status}: ${JSON.stringify(res.json)}`)
  assert((res.json as { lifecycleStatus: string }).lifecycleStatus === 'ChairReview', 'response reports ChairReview status')

  const groupAfter = await prisma.group.findUniqueOrThrow({ where: { id: groupA.id } })
  assert(groupAfter.lifecycleStatus === 'ChairReview', "groupA's lifecycleStatus flipped to ChairReview")

  const comments = await prisma.comment.findMany({ where: { groupId: groupA.id } })
  assert(comments.length === 2, `expected 2 Comment rows, got ${comments.length}`)
  assert(
    comments.every((c) => c.author === 'NetworkAdvisor' && c.dnaVersionId === dnaVersionA.id),
    'every comment is authored by NetworkAdvisor and attached to the current DnaVersion',
  )

  const commentEvents = await prisma.event.findMany({ where: { groupId: groupA.id, type: 'Comment' } })
  assert(commentEvents.length === 1 && commentEvents[0].actorEmail === na1, 'a Comment event was logged for na1')
  console.log('  8. Send to Chair: comments written, status transitioned, event logged ok')

  // --- 9. groupA no longer shows up in na1's list (it's ChairReview now, not Launched).
  res = await call('/api/getNaGroups', { method: 'GET', email: na1 })
  assert((res.json as { groups: unknown[] }).groups.length === 0, "groupA no longer listed for na1 after moving to ChairReview")
  console.log('  9. Sent group drops out of the NA list ok')

  console.log('verify-na-comments: all checks passed')
}

main()
  .catch((err) => {
    console.error(err)
    process.exitCode = 1
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
