import 'dotenv/config'
import { PrismaClient } from '../shared/prismaClient'

// Hits a real running Functions host with hand-built x-ms-client-principal
// headers, same local-auth-stub approach as verify-launch.ts. Exercises
// Admin-only "View as" (api/shared/auth.ts's resolveViewAs, read-only) and
// its write-capable sibling resolveActingAs end to end — the mutating
// Chair/NA endpoints DO honor x-view-as-email now, by design, so an Admin
// can exercise the whole NA-comment → Chair-review → approve flow without
// four other logins. What matters here is that it's exactly as scoped as a
// real Chair/NA's own request would be: ownership-checked against the
// impersonated email, attributed to them (not the Admin), and a non-admin's
// own header is still ignored.
const databaseUrl = process.env.DATABASE_URL ?? ''
const databaseHost = new URL(databaseUrl).hostname
if (databaseHost !== 'localhost' && databaseHost !== '127.0.0.1') {
  throw new Error(`Refusing to run verify-view-as against non-local DATABASE_URL host "${databaseHost}".`)
}

const FUNCTIONS_HOST = process.env.FUNCTIONS_HOST ?? 'http://localhost:7071'
const prisma = new PrismaClient()

function assert(condition: unknown, message: string): asserts condition {
  if (!condition) throw new Error(`Assertion failed: ${message}`)
}

function principalHeader(email: string): string {
  const principal = { userId: email, userDetails: email, identityProvider: 'aad', userRoles: ['authenticated'] }
  return Buffer.from(JSON.stringify(principal), 'utf-8').toString('base64')
}

async function call(path: string, opts: { method: string; email?: string; viewAsEmail?: string; body?: unknown }) {
  const headers: Record<string, string> = { 'Content-Type': 'application/json' }
  if (opts.email) headers['x-ms-client-principal'] = principalHeader(opts.email)
  if (opts.viewAsEmail) headers['x-view-as-email'] = opts.viewAsEmail
  const res = await fetch(`${FUNCTIONS_HOST}${path}`, {
    method: opts.method,
    headers,
    body: opts.body !== undefined ? JSON.stringify(opts.body) : undefined,
  })
  const json = res.status === 204 ? null : await res.json().catch(() => null)
  return { status: res.status, json }
}

async function main() {
  await prisma.aiConversationTurn.deleteMany({})
  await prisma.comment.deleteMany({})
  await prisma.event.deleteMany({})
  await prisma.dnaVersion.deleteMany({})
  await prisma.group.deleteMany({})
  await prisma.user.deleteMany({})

  const adminEmail = 'admin@example.com'
  const chairEmail = 'chair@example.com'
  const naEmail = 'na@example.com'
  await prisma.user.create({ data: { email: adminEmail, name: 'Admin', initials: 'AD', roles: ['Admin'] } })
  await prisma.user.create({ data: { email: chairEmail, name: 'Chair Person', initials: 'CP', roles: ['Chair'] } })
  await prisma.user.create({ data: { email: naEmail, name: 'NA Person', initials: 'NP', roles: ['NetworkAdvisor'], hasSeenNaGuidance: true } })

  const chairGroup = await prisma.group.create({
    data: {
      egnGroupId: 'verify-view-as-1',
      partnerCode: 'EGDK',
      country: 'Denmark',
      name: 'Verify View As — Chair Group',
      lifecycleStatus: 'ChairReview',
      chairEmail,
      groupProfile: 'GROUP TEXT',
      memberProfile: 'MEMBER TEXT',
      companiesProfile: 'COMPANIES TEXT',
    },
  })
  const naGroup = await prisma.group.create({
    data: {
      egnGroupId: 'verify-view-as-2',
      partnerCode: 'EGDK',
      country: 'Denmark',
      name: 'Verify View As — NA Group',
      lifecycleStatus: 'Launched',
      networkAdvisorEmail: naEmail,
      groupProfile: 'GROUP TEXT 2',
      memberProfile: 'MEMBER TEXT 2',
      companiesProfile: 'COMPANIES TEXT 2',
    },
  })
  // Both need a DnaVersion — editChairField (via saveChairFieldEdit) and
  // putNaComments both require one to exist, and scenario 5 below exercises
  // real writes through both, not just the read endpoints.
  await prisma.dnaVersion.create({
    data: {
      groupId: chairGroup.id,
      versionNumber: 1,
      content: { groupProfile: 'GROUP TEXT', memberProfile: 'MEMBER TEXT', companiesProfile: 'COMPANIES TEXT' },
      author: 'Ai',
      scoreStage: 'AutoGenerated',
    },
  })
  await prisma.dnaVersion.create({
    data: {
      groupId: naGroup.id,
      versionNumber: 1,
      content: { groupProfile: 'GROUP TEXT 2', memberProfile: 'MEMBER TEXT 2', companiesProfile: 'COMPANIES TEXT 2' },
      author: 'Ai',
      scoreStage: 'AutoGenerated',
    },
  })

  // --- 1. A non-admin sending the header is silently ignored — they just
  // get their own (empty) data, not an error, and definitely not the target's.
  let res = await call('/api/getChairGroups', { method: 'GET', email: chairEmail, viewAsEmail: 'someone-else@example.com' })
  assert(res.status === 200, `expected 200 for a Chair's own getChairGroups even with a (bogus) view-as header, got ${res.status}`)
  assert(res.json.groups.length === 1 && res.json.groups[0].id === chairGroup.id, "a non-admin's view-as header is ignored — they see their own groups")

  // --- 2. A real Admin, no header: their own (empty) view — the header
  // being absent must not accidentally grant them Chair/NA data.
  res = await call('/api/getChairGroups', { method: 'GET', email: adminEmail })
  assert(res.status === 403, `expected 403 for an Admin calling getChairGroups with no view-as header (they hold no Chair role), got ${res.status}`)
  console.log('  1-2. Non-admin view-as header ignored; admin-with-no-header still 403s ok')

  // --- 3. A real Admin, with the header: sees the target Chair's real groups.
  res = await call('/api/getChairGroups', { method: 'GET', email: adminEmail, viewAsEmail: chairEmail })
  assert(res.status === 200, `expected 200 for Admin view-as Chair on getChairGroups, got ${res.status}: ${JSON.stringify(res.json)}`)
  assert(res.json.groups.length === 1 && res.json.groups[0].id === chairGroup.id, 'Admin view-as Chair sees the real Chair-owned group')

  res = await call(`/api/getChairGroup?groupId=${chairGroup.id}`, { method: 'GET', email: adminEmail, viewAsEmail: chairEmail })
  assert(res.status === 200, `expected 200 for Admin view-as Chair on getChairGroup, got ${res.status}: ${JSON.stringify(res.json)}`)
  assert(res.json.id === chairGroup.id, "Admin view-as Chair's getChairGroup detail matches the real group")
  console.log('  3. Admin view-as a real Chair sees that Chair\'s real list + detail ok')

  // --- 4. Same for Network Advisor — and showGuidance is suppressed
  // (never the Admin's own irrelevant flag, never the target's real one).
  res = await call('/api/getNaGroups', { method: 'GET', email: adminEmail, viewAsEmail: naEmail })
  assert(res.status === 200, `expected 200 for Admin view-as NA on getNaGroups, got ${res.status}: ${JSON.stringify(res.json)}`)
  assert(res.json.groups.length === 1 && res.json.groups[0].id === naGroup.id, 'Admin view-as NA sees the real NA-owned group')
  assert(res.json.showGuidance === false, 'showGuidance is suppressed while viewing as someone, even though the real NA has already seen it')
  console.log('  4. Admin view-as a real Network Advisor sees their real groups, guidance banner suppressed ok')

  // --- 5. Admin "View as" performs REAL writes as the target person —
  // editChairField/approveChairField/putNaComments all honor the header
  // (resolveActingAs), and the write is attributed to the impersonated
  // person, not the Admin driving it.
  res = await call('/api/editChairField', {
    method: 'POST',
    email: adminEmail,
    viewAsEmail: chairEmail,
    body: { groupId: chairGroup.id, field: 'GroupProfile', text: 'EDITED VIA ADMIN ACTING AS CHAIR' },
  })
  assert(res.status === 200, `expected 200 for Admin acting-as Chair editing a field, got ${res.status}: ${JSON.stringify(res.json)}`)
  const groupAfterActingAsEdit = await prisma.group.findUniqueOrThrow({ where: { id: chairGroup.id } })
  assert(groupAfterActingAsEdit.groupProfile === 'EDITED VIA ADMIN ACTING AS CHAIR', "Admin acting-as Chair's edit actually wrote the group's live text")
  const editEvent = await prisma.event.findFirst({ where: { groupId: chairGroup.id, type: 'Edit' } })
  assert(editEvent?.actorEmail === chairEmail, 'the Edit event is attributed to the real Chair, not the Admin driving it')

  res = await call('/api/approveChairField', { method: 'POST', email: adminEmail, viewAsEmail: chairEmail, body: { groupId: chairGroup.id, field: 'MemberProfile' } })
  assert(res.status === 200, `expected 200 for Admin acting-as Chair approving a field, got ${res.status}: ${JSON.stringify(res.json)}`)
  const groupAfterActingAsApprove = await prisma.group.findUniqueOrThrow({ where: { id: chairGroup.id } })
  assert(groupAfterActingAsApprove.approvedFields.includes('MemberProfile'), "Admin acting-as Chair's approval actually recorded")

  res = await call('/api/putNaComments', {
    method: 'POST',
    email: adminEmail,
    viewAsEmail: naEmail,
    body: { groupId: naGroup.id, comments: [{ field: 'GroupProfile', text: 'Comment sent via Admin acting as the NA' }] },
  })
  assert(res.status === 200, `expected 200 for Admin acting-as NA sending a comment, got ${res.status}: ${JSON.stringify(res.json)}`)
  const naGroupAfterActingAs = await prisma.group.findUniqueOrThrow({ where: { id: naGroup.id } })
  assert(naGroupAfterActingAs.lifecycleStatus === 'ChairReview', "Admin acting-as NA's comment actually moved the group to ChairReview")
  const commentEvent = await prisma.event.findFirst({ where: { groupId: naGroup.id, type: 'Comment' } })
  assert(commentEvent?.actorEmail === naEmail, 'the Comment event is attributed to the real NA, not the Admin driving it')
  console.log('  5. Admin "View as" performs real writes as the target — attributed to them, not the Admin ok')

  // --- 6. Ownership scoping still holds while acting-as: an Admin cannot
  // act as a Chair on a group that isn't actually assigned to that Chair —
  // the header only selects whose ownership check runs, it doesn't bypass it.
  res = await call('/api/editChairField', {
    method: 'POST',
    email: adminEmail,
    viewAsEmail: chairEmail,
    body: { groupId: naGroup.id, field: 'GroupProfile', text: 'should never land' },
  })
  assert(res.status === 404, `expected 404 acting as a Chair not assigned to this group, got ${res.status}`)
  console.log('  6. Ownership scoping still enforced while acting-as ok')

  // --- 7. A non-admin's own view-as header is still ignored on a write
  // endpoint too — they can only ever act as themselves.
  res = await call('/api/editChairField', {
    method: 'POST',
    email: chairEmail,
    viewAsEmail: 'someone-else@example.com',
    body: { groupId: chairGroup.id, field: 'CompaniesProfile', text: 'edited by the real chair, header ignored' },
  })
  assert(res.status === 200, `expected 200 — a non-admin editing their own group, got ${res.status}: ${JSON.stringify(res.json)}`)
  const groupAfterSelfEdit = await prisma.group.findUniqueOrThrow({ where: { id: chairGroup.id } })
  assert(groupAfterSelfEdit.companiesProfile === 'edited by the real chair, header ignored', 'the edit went through as the real Chair')
  const lastEditEvent = await prisma.event.findFirst({ where: { groupId: chairGroup.id, type: 'Edit' }, orderBy: { timestamp: 'desc' } })
  assert(lastEditEvent?.actorEmail === chairEmail, "attributed to the real Chair themselves — a non-admin's bogus header names nobody")
  console.log('  7. A non-admin\'s own view-as header is ignored on a write endpoint too ok')

  // --- 8. getMe now carries name/initials too.
  res = await call('/api/getMe', { method: 'GET', email: chairEmail })
  assert(res.status === 200 && res.json.name === 'Chair Person' && res.json.initials === 'CP', `expected getMe to include the real name/initials, got ${JSON.stringify(res.json)}`)
  console.log('  8. getMe exposes name/initials ok')

  console.log('verify-view-as: all checks passed')
}

main()
  .catch((err) => {
    console.error(err)
    process.exitCode = 1
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
