import 'dotenv/config'
import { PrismaClient } from '../shared/prismaClient'

// Hits a real running Functions host with hand-built x-ms-client-principal
// headers, same local-auth-stub approach as verify-launch.ts. No AI calls —
// generateDnaStage1/2's own pipeline is already covered end-to-end by
// verify-dna-generation.ts; this script only exercises the NEW surface
// added for the Groups tab's Generate/Score/Launch UI (issue #13):
// getGroups' latestDnaVersionId/latestDnaVersionScore/hasPendingAiDraft
// fields, and the new getGroup detail endpoint — so DnaVersions are
// created directly, the same way verify-score-dna-version.ts does.
const databaseUrl = process.env.DATABASE_URL ?? ''
const databaseHost = new URL(databaseUrl).hostname
if (databaseHost !== 'localhost' && databaseHost !== '127.0.0.1') {
  throw new Error(`Refusing to run verify-admin-groups against non-local DATABASE_URL host "${databaseHost}".`)
}

const FUNCTIONS_HOST = process.env.FUNCTIONS_HOST ?? 'http://localhost:7071'
const prisma = new PrismaClient()

function assert(condition: unknown, message: string): asserts condition {
  if (!condition) throw new Error(`Assertion failed: ${message}`)
}

function principalHeader(email: string): string {
  const principal = { userId: email, userDetails: email, identityProvider: 'aad', userRoles: ['authenticated'] }
  return Buffer.from(JSON.stringify(principal), 'utf-8').toString('base64')
}

async function call(path: string, opts: { method: string; email?: string; body?: unknown }) {
  const headers: Record<string, string> = { 'Content-Type': 'application/json' }
  if (opts.email) headers['x-ms-client-principal'] = principalHeader(opts.email)
  const res = await fetch(`${FUNCTIONS_HOST}${path}`, {
    method: opts.method,
    headers,
    body: opts.body !== undefined ? JSON.stringify(opts.body) : undefined,
  })
  const json = res.status === 204 ? null : await res.json().catch(() => null)
  return { status: res.status, json }
}

async function main() {
  await prisma.aiConversationTurn.deleteMany({})
  await prisma.comment.deleteMany({})
  await prisma.event.deleteMany({})
  await prisma.dnaVersion.deleteMany({})
  await prisma.group.deleteMany({})
  await prisma.user.deleteMany({})

  const adminEmail = 'admin@example.com'
  const chairEmail = 'chair@example.com'
  await prisma.user.create({ data: { email: adminEmail, name: 'Admin', initials: 'AD', roles: ['Admin'] } })
  await prisma.user.create({ data: { email: chairEmail, name: 'Chair Person', initials: 'CP', roles: ['Chair'] } })

  // --- Group A: no DnaVersion yet (never generated).
  const groupA = await prisma.group.create({
    data: {
      egnGroupId: 'verify-admin-groups-a',
      partnerCode: 'EGDK',
      country: 'Denmark',
      name: 'Verify Admin Groups A',
      groupProfile: 'plain group profile',
      memberProfile: 'plain member profile',
      companiesProfile: 'plain companies profile',
    },
  })

  // --- Group B: has an Imported-stage version (v1) and an AutoGenerated
  // AI draft on top (v2) — the "pending AI draft" case.
  const groupB = await prisma.group.create({
    data: {
      egnGroupId: 'verify-admin-groups-b',
      partnerCode: 'EGDK',
      country: 'Denmark',
      name: 'Verify Admin Groups B',
      groupProfile: 'original group profile',
      memberProfile: 'original member profile',
      companiesProfile: 'original companies profile',
    },
  })
  await prisma.dnaVersion.create({
    data: {
      groupId: groupB.id,
      versionNumber: 1,
      content: { groupProfile: 'original group profile', memberProfile: 'original member profile', companiesProfile: 'original companies profile' },
      author: null,
      scoreStage: 'Imported',
    },
  })
  const draftVersion = await prisma.dnaVersion.create({
    data: {
      groupId: groupB.id,
      versionNumber: 2,
      content: { groupProfile: 'draft group profile', memberProfile: 'draft member profile', companiesProfile: 'draft companies profile' },
      author: 'Ai',
      score: 4,
      scoreStage: 'AutoGenerated',
    },
  })

  // --- Group C: latest version is Chair-authored, not Ai — must NOT be reported as a pending AI draft.
  const groupC = await prisma.group.create({
    data: {
      egnGroupId: 'verify-admin-groups-c',
      partnerCode: 'EGDK',
      country: 'Denmark',
      name: 'Verify Admin Groups C',
      groupProfile: 'chair-edited group profile',
      memberProfile: 'chair-edited member profile',
      companiesProfile: 'chair-edited companies profile',
    },
  })
  await prisma.dnaVersion.create({
    data: {
      groupId: groupC.id,
      versionNumber: 1,
      content: { groupProfile: 'chair-edited group profile', memberProfile: 'chair-edited member profile', companiesProfile: 'chair-edited companies profile' },
      author: 'Chair',
      score: 5,
      scoreStage: 'ChairEdited',
    },
  })

  // --- 1. Auth/role guards.
  let res = await call('/api/getGroups', { method: 'GET' })
  assert(res.status === 401, `expected 401 for unauthenticated getGroups, got ${res.status}`)
  res = await call('/api/getGroups', { method: 'GET', email: chairEmail })
  assert(res.status === 403, `expected 403 for a Chair calling getGroups, got ${res.status}`)
  res = await call(`/api/getGroup?groupId=${groupA.id}`, { method: 'GET' })
  assert(res.status === 401, `expected 401 for unauthenticated getGroup, got ${res.status}`)
  res = await call(`/api/getGroup?groupId=${groupA.id}`, { method: 'GET', email: chairEmail })
  assert(res.status === 403, `expected 403 for a Chair calling getGroup, got ${res.status}`)
  console.log('  1. Auth/role guards (401/403) on getGroups and getGroup ok')

  // --- 2. getGroup not-found.
  res = await call('/api/getGroup?groupId=does-not-exist', { method: 'GET', email: adminEmail })
  assert(res.status === 404, `expected 404 for a nonexistent group, got ${res.status}`)
  console.log('  2. getGroup 404 for a nonexistent group ok')

  // --- 3. getGroups' new fields, across all three cases.
  res = await call('/api/getGroups', { method: 'GET', email: adminEmail })
  assert(res.status === 200, `expected 200 for admin getGroups, got ${res.status}`)
  type ListedGroup = { id: string; latestDnaVersionId: string | null; latestDnaVersionScore: number | null; hasPendingAiDraft: boolean }
  const listById = new Map((res.json as ListedGroup[]).map((g) => [g.id, g] as const))
  const a = listById.get(groupA.id)!
  assert(a.latestDnaVersionId === null, 'group A (never generated) has latestDnaVersionId null')
  assert(a.latestDnaVersionScore === null, 'group A has latestDnaVersionScore null')
  assert(a.hasPendingAiDraft === false, 'group A has hasPendingAiDraft false')
  const b = listById.get(groupB.id)!
  assert(b.latestDnaVersionId === draftVersion.id, "group B's latestDnaVersionId is its v2 (AutoGenerated) version")
  assert(b.latestDnaVersionScore === 4, 'group B latestDnaVersionScore is 4')
  assert(b.hasPendingAiDraft === true, 'group B hasPendingAiDraft is true (latest version author is Ai)')
  const c = listById.get(groupC.id)!
  assert(c.latestDnaVersionId !== null, 'group C has a latestDnaVersionId (a Chair-authored version exists)')
  assert(c.hasPendingAiDraft === false, "group C hasPendingAiDraft is false — latest version's author is Chair, not Ai")
  console.log('  3. getGroups latestDnaVersionId/latestDnaVersionScore/hasPendingAiDraft ok for all 3 cases')

  // --- 4. getGroup detail: no version yet.
  res = await call(`/api/getGroup?groupId=${groupA.id}`, { method: 'GET', email: adminEmail })
  assert(res.status === 200, `expected 200 for admin getGroup on group A, got ${res.status}`)
  assert(res.json.latestDnaVersion === null, 'group A detail has latestDnaVersion null')
  assert(res.json.groupProfile === 'plain group profile', "group A detail falls back to the Group's own plain fields")
  console.log('  4. getGroup detail for a never-generated group ok')

  // --- 5. getGroup detail: pending AI draft — content comes from the DnaVersion, not Group's plain fields.
  res = await call(`/api/getGroup?groupId=${groupB.id}`, { method: 'GET', email: adminEmail })
  assert(res.status === 200, `expected 200 for admin getGroup on group B, got ${res.status}`)
  const detailB = res.json as { latestDnaVersion: { id: string; versionNumber: number; author: string; score: number; scoreStage: string; content: { groupProfile: string } } }
  assert(detailB.latestDnaVersion.id === draftVersion.id, "group B detail's latestDnaVersion is the v2 draft")
  assert(detailB.latestDnaVersion.versionNumber === 2, 'group B detail latestDnaVersion versionNumber is 2')
  assert(detailB.latestDnaVersion.author === 'Ai', 'group B detail latestDnaVersion author is Ai')
  assert(detailB.latestDnaVersion.score === 4, 'group B detail latestDnaVersion score is 4')
  assert(detailB.latestDnaVersion.scoreStage === 'AutoGenerated', 'group B detail latestDnaVersion scoreStage is AutoGenerated')
  assert(detailB.latestDnaVersion.content.groupProfile === 'draft group profile', "group B detail's DNA content is the unlaunched AI draft, not Group's plain fields")

  console.log('  5. getGroup detail exposes the unlaunched AI draft content ok')

  console.log('verify-admin-groups: all checks passed')
}

main()
  .catch((err) => {
    console.error(err)
    process.exitCode = 1
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
