import { render, screen, fireEvent, waitFor } from '@testing-library/react'
import { describe, expect, it, vi, beforeEach } from 'vitest'
import ImportGroups from './ImportGroups'

const chair = { email: 'chair@example.com', name: 'Chair Person', initials: 'CP', roles: ['Chair'] }
const advisor = { email: 'na@example.com', name: 'NA Person', initials: 'NP', roles: ['NetworkAdvisor'] }

const group = {
  id: 'g1',
  egnGroupId: '38494',
  name: 'Test Group',
  mmsGroupCode: '02092-EGDK',
  partnerCode: 'EGDK',
  country: 'Denmark',
  chairEmail: null,
  networkAdvisorEmail: null,
  lifecycleStatus: 'Imported',
  noSourceDna: false,
  emptySectionCount: 1,
  latestDnaVersionId: null,
  latestDnaVersionScore: null,
  hasPendingAiDraft: false,
}

const groupDetail = {
  id: 'g1',
  egnGroupId: '38494',
  name: 'Test Group',
  country: 'Denmark',
  chairEmail: null,
  networkAdvisorEmail: null,
  lifecycleStatus: 'DraftGenerated',
  groupProfile: 'original group profile',
  memberProfile: 'original member profile',
  companiesProfile: 'original companies profile',
  latestDnaVersion: {
    id: 'v2',
    versionNumber: 2,
    author: 'Ai',
    score: 4,
    scoreStage: 'AutoGenerated',
    createdAt: '2026-08-01T00:00:00.000Z',
    content: { groupProfile: 'draft group profile', memberProfile: 'draft member profile', companiesProfile: 'draft companies profile' },
  },
}

function mockFetch(handlers: {
  getUsers?: unknown
  getGroups?: unknown
  checkGroupImport?: unknown
  putGroups?: { status: number; body: unknown }
  getGroup?: unknown
  generateDnaStage1?: { status: number; body: unknown }
  generateDnaStage2?: { status: number; body: unknown }
  scoreDna?: { status: number; body: unknown }
  commitDnaGeneration?: { status: number; body: unknown }
  scoreDnaVersion?: { status: number; body: unknown }
  launchGroup?: { status: number; body: unknown }
}) {
  return vi.fn(async (url: string) => {
    if (url === '/api/getUsers') return { ok: true, status: 200, json: async () => handlers.getUsers ?? [] }
    if (url === '/api/getGroups') return { ok: true, status: 200, json: async () => handlers.getGroups ?? [] }
    if (url === '/api/checkGroupImport') return { ok: true, status: 200, json: async () => handlers.checkGroupImport ?? [] }
    if (url === '/api/putGroups') {
      const { status, body } = handlers.putGroups ?? { status: 200, body: { created: [], overwritten: [] } }
      return { ok: status < 300, status, json: async () => body }
    }
    if (url.startsWith('/api/getGroup?')) return { ok: true, status: 200, json: async () => handlers.getGroup ?? groupDetail }
    if (url === '/api/generateDnaStage1') {
      const { status, body } = handlers.generateDnaStage1 ?? { status: 200, body: { stage1Text: 'stage1' } }
      return { ok: status < 300, status, json: async () => body }
    }
    if (url === '/api/generateDnaStage2') {
      const { status, body } = handlers.generateDnaStage2 ?? { status: 200, body: { stage2Text: 'stage2' } }
      return { ok: status < 300, status, json: async () => body }
    }
    if (url === '/api/scoreDna') {
      const { status, body } = handlers.scoreDna ?? { status: 200, body: { score: 4 } }
      return { ok: status < 300, status, json: async () => body }
    }
    if (url === '/api/commitDnaGeneration') {
      const { status, body } = handlers.commitDnaGeneration ?? { status: 200, body: { importedVersionId: 'v1', autoGeneratedVersionId: 'v2' } }
      return { ok: status < 300, status, json: async () => body }
    }
    if (url === '/api/scoreDnaVersion') {
      const { status, body } = handlers.scoreDnaVersion ?? { status: 200, body: { dnaVersionId: 'v2', score: 4 } }
      return { ok: status < 300, status, json: async () => body }
    }
    if (url === '/api/launchGroup') {
      const { status, body } = handlers.launchGroup ?? { status: 200, body: { groupId: 'g1', lifecycleStatus: 'Launched', launchedVersionNumber: 2 } }
      return { ok: status < 300, status, json: async () => body }
    }
    throw new Error(`Unexpected fetch: ${url}`)
  })
}

describe('ImportGroups', () => {
  beforeEach(() => {
    vi.unstubAllGlobals()
  })

  it('renders imported groups with quality chips', async () => {
    vi.stubGlobal('fetch', mockFetch({ getGroups: [group] }))
    render(<ImportGroups />)

    await waitFor(() => {
      expect(screen.getByText('Test Group')).toBeInTheDocument()
    })
    expect(screen.getByText('1 empty section(s)')).toBeInTheDocument()
    expect(screen.getByText('no Chair')).toBeInTheDocument()
    expect(screen.getByText('no NA')).toBeInTheDocument()
  })

  it('checks a manually entered group and shows it in the review table', async () => {
    const fetchMock = mockFetch({
      getUsers: [chair, advisor],
      checkGroupImport: [
        {
          row: {
            egnGroupName: 'New Group',
            egnGroupId: '999',
            mmsGroupCode: 'MMS-1',
            partnerCode: 'EGDK',
            groupProfile: '',
            memberProfile: '',
            companiesProfile: '',
            responsibleChairName: 'Chair Person',
            responsibleChairEmail: chair.email,
            responsibleSalesName: 'NA Person',
            responsibleSalesEmail: advisor.email,
          },
          status: 'new',
          existingGroupId: null,
          suggestedChairEmail: chair.email,
          suggestedNetworkAdvisorEmail: advisor.email,
        },
      ],
    })
    vi.stubGlobal('fetch', fetchMock)
    render(<ImportGroups />)

    fireEvent.change(screen.getByLabelText('EGN Group Name'), { target: { value: 'New Group' } })
    fireEvent.change(screen.getByLabelText('EGN Group Id'), { target: { value: '999' } })
    fireEvent.change(screen.getByLabelText('MMSGroup: Name'), { target: { value: 'MMS-1' } })
    fireEvent.change(screen.getByLabelText('Partner Code'), { target: { value: 'EGDK' } })
    fireEvent.change(screen.getByLabelText('Responsible Chair'), { target: { value: 'Chair Person' } })
    fireEvent.change(screen.getByLabelText('Responsible Chair Email'), { target: { value: chair.email } })
    fireEvent.change(screen.getByLabelText('Responsible Sales'), { target: { value: 'NA Person' } })
    fireEvent.change(screen.getByLabelText('Responsible Sales Email'), { target: { value: advisor.email } })
    fireEvent.click(screen.getByText('Check group'))

    await waitFor(() => {
      expect(screen.getByText('Review before import')).toBeInTheDocument()
    })
    expect(screen.getByText('New Group')).toBeInTheDocument()
    expect(screen.getByText('New')).toBeInTheDocument()
    // Best-guess Chair/NA should be pre-selected.
    expect(screen.getByLabelText('Chair for New Group')).toHaveValue(chair.email)
    expect(screen.getByLabelText('Network Advisor for New Group')).toHaveValue(advisor.email)

    fireEvent.click(screen.getByText('Confirm import'))

    await waitFor(() => {
      expect(fetchMock).toHaveBeenCalledWith(
        '/api/putGroups',
        expect.objectContaining({
          method: 'POST',
          body: expect.stringContaining('"egnGroupId":"999"'),
        }),
      )
    })
  })

  it('shows an unmatched Chair/NA email as "— unmatched —", not silently guessed or auto-created', async () => {
    const fetchMock = mockFetch({
      getUsers: [chair, advisor],
      checkGroupImport: [
        {
          row: {
            egnGroupName: 'New Group',
            egnGroupId: '999',
            mmsGroupCode: 'MMS-1',
            partnerCode: 'EGDK',
            groupProfile: '',
            memberProfile: '',
            companiesProfile: '',
            responsibleChairName: 'Someone Not Yet A User',
            responsibleChairEmail: 'not-a-user-yet@example.com',
            responsibleSalesName: 'NA Person',
            responsibleSalesEmail: advisor.email,
          },
          status: 'new',
          existingGroupId: null,
          // checkGroupImport itself found no matching User for this email —
          // this is what it returns in that case.
          suggestedChairEmail: null,
          suggestedNetworkAdvisorEmail: advisor.email,
        },
      ],
    })
    vi.stubGlobal('fetch', fetchMock)
    render(<ImportGroups />)

    fireEvent.change(screen.getByLabelText('EGN Group Name'), { target: { value: 'New Group' } })
    fireEvent.change(screen.getByLabelText('EGN Group Id'), { target: { value: '999' } })
    fireEvent.change(screen.getByLabelText('MMSGroup: Name'), { target: { value: 'MMS-1' } })
    fireEvent.change(screen.getByLabelText('Partner Code'), { target: { value: 'EGDK' } })
    fireEvent.change(screen.getByLabelText('Responsible Chair'), { target: { value: 'Someone Not Yet A User' } })
    fireEvent.change(screen.getByLabelText('Responsible Chair Email'), { target: { value: 'not-a-user-yet@example.com' } })
    fireEvent.change(screen.getByLabelText('Responsible Sales'), { target: { value: 'NA Person' } })
    fireEvent.change(screen.getByLabelText('Responsible Sales Email'), { target: { value: advisor.email } })
    fireEvent.click(screen.getByText('Check group'))

    await waitFor(() => {
      expect(screen.getByText('Review before import')).toBeInTheDocument()
    })
    expect(screen.getByLabelText('Chair for New Group')).toHaveValue('')
    expect(screen.getByLabelText('Network Advisor for New Group')).toHaveValue(advisor.email)
  })

  it('rejects a non-UTF-8 CSV file with a clear banner', async () => {
    vi.stubGlobal('fetch', mockFetch({}))
    render(<ImportGroups />)

    // 0xE6 alone is invalid UTF-8 (a lone continuation-expecting lead byte).
    const badBytes = new Uint8Array([0x68, 0x65, 0x6c, 0x6c, 0x6f, 0xe6])
    const file = new File([badBytes], 'groups.csv', { type: 'text/csv' })
    const input = screen.getByLabelText('CSV file')
    fireEvent.change(input, { target: { files: [file] } })

    await waitFor(() => {
      expect(screen.getByRole('alert')).toHaveTextContent('This file is not saved as UTF-8 — import blocked')
    })
  })

  it('disables Score and Launch until a DNA version exists / an AI draft is pending', async () => {
    vi.stubGlobal('fetch', mockFetch({ getGroups: [group] }))
    render(<ImportGroups />)

    await waitFor(() => {
      expect(screen.getByText('Test Group')).toBeInTheDocument()
    })
    expect(screen.getByText('No DNA version yet')).toBeInTheDocument()
    const scoreButtons = screen.getAllByText('Score')
    const launchButtons = screen.getAllByText('Launch')
    expect(scoreButtons[0]).toBeDisabled()
    expect(launchButtons[0]).toBeDisabled()
  })

  it('runs the full Generate pipeline from the list row and refreshes the group afterwards', async () => {
    const generatedGroup = { ...group, latestDnaVersionId: 'v2', latestDnaVersionScore: 4, hasPendingAiDraft: true }
    const fetchMock = vi.fn(async (url: string) => {
      if (url === '/api/getUsers') return { ok: true, status: 200, json: async () => [] }
      if (url === '/api/getGroups') return { ok: true, status: 200, json: async () => (fetchMock.mock.calls.filter((c) => c[0] === '/api/getGroups').length > 1 ? [generatedGroup] : [group]) }
      if (url === '/api/generateDnaStage1') return { ok: true, status: 200, json: async () => ({ stage1Text: 'stage1' }) }
      if (url === '/api/generateDnaStage2') return { ok: true, status: 200, json: async () => ({ stage2Text: 'stage2' }) }
      if (url === '/api/scoreDna') return { ok: true, status: 200, json: async () => ({ score: 4 }) }
      if (url === '/api/commitDnaGeneration') return { ok: true, status: 200, json: async () => ({ importedVersionId: 'v1', autoGeneratedVersionId: 'v2' }) }
      throw new Error(`Unexpected fetch: ${url}`)
    })
    vi.stubGlobal('fetch', fetchMock)
    render(<ImportGroups />)

    await waitFor(() => {
      expect(screen.getByText('Test Group')).toBeInTheDocument()
    })
    fireEvent.click(screen.getByText('Generate'))

    await waitFor(() => {
      expect(fetchMock).toHaveBeenCalledWith('/api/generateDnaStage1', expect.objectContaining({ body: JSON.stringify({ groupId: 'g1' }) }))
      expect(fetchMock).toHaveBeenCalledWith('/api/generateDnaStage2', expect.objectContaining({ body: JSON.stringify({ groupId: 'g1', stage1Text: 'stage1' }) }))
      expect(fetchMock).toHaveBeenCalledWith('/api/scoreDna', expect.objectContaining({ body: JSON.stringify({ text: 'stage2' }) }))
      expect(fetchMock).toHaveBeenCalledWith(
        '/api/commitDnaGeneration',
        expect.objectContaining({ body: JSON.stringify({ groupId: 'g1', stage2Text: 'stage2', autoGeneratedScore: 4 }) }),
      )
    })
    await waitFor(() => {
      expect(screen.getByText('AI draft pending, score 4/5')).toBeInTheDocument()
    })
  })

  it('calls launchGroup when Launch is clicked on a group with a pending AI draft', async () => {
    const pendingGroup = { ...group, latestDnaVersionId: 'v2', latestDnaVersionScore: 4, hasPendingAiDraft: true }
    const fetchMock = mockFetch({ getGroups: [pendingGroup] })
    vi.stubGlobal('fetch', fetchMock)
    render(<ImportGroups />)

    await waitFor(() => {
      expect(screen.getByText('Test Group')).toBeInTheDocument()
    })
    fireEvent.click(screen.getByText('Launch'))

    await waitFor(() => {
      expect(fetchMock).toHaveBeenCalledWith('/api/launchGroup', expect.objectContaining({ body: JSON.stringify({ groupId: 'g1' }) }))
    })
  })

  it('opens a group detail view showing the latest DNA version content, reachable from the list', async () => {
    vi.stubGlobal('fetch', mockFetch({ getGroups: [group] }))
    render(<ImportGroups />)

    await waitFor(() => {
      expect(screen.getByText('Test Group')).toBeInTheDocument()
    })
    fireEvent.click(screen.getByText('Test Group'))

    await waitFor(() => {
      expect(screen.getByText('Latest DNA version (v2, Ai)')).toBeInTheDocument()
    })
    expect(screen.getByText('draft group profile')).toBeInTheDocument()
    expect(screen.getByText(/^Score 4\/5 ·/)).toBeInTheDocument()

    fireEvent.click(screen.getByText('← Back to groups'))
    await waitFor(() => {
      expect(screen.getByText('Import groups')).toBeInTheDocument()
    })
  })
})
