import { render, screen, fireEvent, waitFor, within } from './test-utils'
import { describe, expect, it, vi, beforeEach } from 'vitest'
import ImportGroups from './ImportGroups'

const chair = { email: 'chair@example.com', name: 'Chair Person', initials: 'CP', roles: ['Chair'] }
const advisor = { email: 'na@example.com', name: 'NA Person', initials: 'NP', roles: ['NetworkAdvisor'] }

const group = {
  id: 'g1',
  egnGroupId: '38494',
  name: 'Test Group',
  mmsGroupCode: '02092-EGDK',
  partnerCode: 'EGDK',
  country: 'Denmark',
  chairEmail: null,
  networkAdvisorEmail: null,
  lifecycleStatus: 'Imported',
  noSourceDna: false,
  emptySectionCount: 1,
  updatedAt: '2026-05-12T10:00:00.000Z',
  latestDnaVersionId: null,
  latestDnaVersionScore: null,
  hasPendingAiDraft: false,
}

const groupDetail = {
  id: 'g1',
  egnGroupId: '38494',
  mmsGroupCode: '02092-EGDK',
  name: 'Test Group',
  country: 'Denmark',
  chairEmail: null,
  networkAdvisorEmail: null,
  lifecycleStatus: 'DraftGenerated',
  groupProfile: 'original group profile',
  memberProfile: 'original member profile',
  companiesProfile: 'original companies profile',
  latestDnaVersion: {
    id: 'v2',
    versionNumber: 2,
    author: 'Ai',
    score: 4,
    scoreStage: 'AutoGenerated',
    createdAt: '2026-08-01T00:00:00.000Z',
    content: { groupProfile: 'draft group profile', memberProfile: 'draft member profile', companiesProfile: 'draft companies profile' },
  },
  importedSnapshot: null,
  roster: null,
}

function mockFetch(handlers: {
  getUsers?: unknown
  getGroups?: unknown
  checkGroupImport?: unknown
  putGroups?: { status: number; body: unknown }
  getGroup?: unknown
  generateDnaStage1?: { status: number; body: unknown }
  generateDnaStage2?: { status: number; body: unknown }
  scoreDna?: { status: number; body: unknown }
  commitDnaGeneration?: { status: number; body: unknown }
  scoreDnaVersion?: { status: number; body: unknown }
  launchGroup?: { status: number; body: unknown }
  reassignGroup?: { status: number; body: unknown }
  editGroup?: { status: number; body: unknown }
  deleteGroup?: { status: number; body: unknown }
  resetGroup?: { status: number; body: unknown }
  saveGroupRoster?: { status: number; body: unknown }
}) {
  return vi.fn(async (url: string) => {
    if (url === '/api/getUsers') return { ok: true, status: 200, json: async () => handlers.getUsers ?? [] }
    if (url === '/api/getGroups') return { ok: true, status: 200, json: async () => handlers.getGroups ?? [] }
    if (url === '/api/checkGroupImport') return { ok: true, status: 200, json: async () => handlers.checkGroupImport ?? [] }
    if (url === '/api/putGroups') {
      const { status, body } = handlers.putGroups ?? { status: 200, body: { created: [], overwritten: [] } }
      return { ok: status < 300, status, json: async () => body }
    }
    if (url.startsWith('/api/getGroup?')) return { ok: true, status: 200, json: async () => handlers.getGroup ?? groupDetail }
    if (url === '/api/generateDnaStage1') {
      const { status, body } = handlers.generateDnaStage1 ?? { status: 200, body: { stage1Text: 'stage1' } }
      return { ok: status < 300, status, json: async () => body }
    }
    if (url === '/api/generateDnaStage2') {
      const { status, body } = handlers.generateDnaStage2 ?? { status: 200, body: { stage2Text: 'stage2' } }
      return { ok: status < 300, status, json: async () => body }
    }
    if (url === '/api/scoreDna') {
      const { status, body } = handlers.scoreDna ?? { status: 200, body: { score: 4 } }
      return { ok: status < 300, status, json: async () => body }
    }
    if (url === '/api/commitDnaGeneration') {
      const { status, body } = handlers.commitDnaGeneration ?? { status: 200, body: { importedVersionId: 'v1', autoGeneratedVersionId: 'v2' } }
      return { ok: status < 300, status, json: async () => body }
    }
    if (url === '/api/scoreDnaVersion') {
      const { status, body } = handlers.scoreDnaVersion ?? { status: 200, body: { dnaVersionId: 'v2', score: 4 } }
      return { ok: status < 300, status, json: async () => body }
    }
    if (url === '/api/launchGroup') {
      const { status, body } = handlers.launchGroup ?? { status: 200, body: { groupId: 'g1', lifecycleStatus: 'Launched', launchedVersionNumber: 2 } }
      return { ok: status < 300, status, json: async () => body }
    }
    if (url === '/api/reassignGroup') {
      const { status, body } = handlers.reassignGroup ?? { status: 200, body: { groupId: 'g1', chairEmail: null, networkAdvisorEmail: null } }
      return { ok: status < 300, status, json: async () => body }
    }
    if (url === '/api/editGroup') {
      const { status, body } = handlers.editGroup ?? { status: 200, body: { ...groupDetail, pendingReapproval: false } }
      return { ok: status < 300, status, json: async () => body }
    }
    if (url === '/api/deleteGroup') {
      const { status, body } = handlers.deleteGroup ?? { status: 200, body: { groupId: 'g1' } }
      return { ok: status < 300, status, json: async () => body }
    }
    if (url === '/api/resetGroup') {
      const { status, body } = handlers.resetGroup ?? { status: 200, body: { ...groupDetail, pendingReapproval: false } }
      return { ok: status < 300, status, json: async () => body }
    }
    if (url === '/api/saveGroupRoster') {
      const { status, body } = handlers.saveGroupRoster ?? { status: 200, body: { groupId: 'g1', roster: null } }
      return { ok: status < 300, status, json: async () => body }
    }
    throw new Error(`Unexpected fetch: ${url}`)
  })
}

describe('ImportGroups', () => {
  beforeEach(() => {
    vi.unstubAllGlobals()
  })

  it('renders the group with its status pill, quality warning, code subtitle, and updated date', async () => {
    vi.stubGlobal('fetch', mockFetch({ getGroups: [group] }))
    render(<ImportGroups />)

    await waitFor(() => {
      expect(screen.getByText('Test Group')).toBeInTheDocument()
    })
    expect(screen.getByText('Imported')).toBeInTheDocument()
    expect(screen.getByText('02092-EGDK')).toBeInTheDocument()
    expect(screen.getByText('12 May 2026')).toBeInTheDocument()
    expect(screen.getByTitle('1 empty section(s), no Chair, no NA')).toBeInTheDocument()
  })

  it('shows the groups list by default, with Import CSV / Add group hidden behind buttons', async () => {
    vi.stubGlobal('fetch', mockFetch({ getGroups: [group] }))
    render(<ImportGroups />)

    await waitFor(() => {
      expect(screen.getByText('Test Group')).toBeInTheDocument()
    })
    expect(screen.queryByLabelText('EGN Group Name')).not.toBeInTheDocument()
    expect(screen.queryByLabelText('CSV file')).not.toBeInTheDocument()

    fireEvent.click(screen.getByText('Add group'))
    expect(screen.getByLabelText('EGN Group Name')).toBeInTheDocument()
    expect(screen.queryByLabelText('CSV file')).not.toBeInTheDocument()

    fireEvent.click(screen.getByText('Import CSV'))
    expect(screen.getByLabelText('CSV file')).toBeInTheDocument()
    expect(screen.queryByLabelText('EGN Group Name')).not.toBeInTheDocument()
  })

  it('checks a manually entered group and shows it in the review table', async () => {
    const fetchMock = mockFetch({
      getUsers: [chair, advisor],
      checkGroupImport: [
        {
          row: {
            egnGroupName: 'New Group',
            egnGroupId: '999',
            mmsGroupCode: 'MMS-1',
            partnerCode: 'EGDK',
            groupProfile: '',
            memberProfile: '',
            companiesProfile: '',
            responsibleChairName: 'Chair Person',
            responsibleChairEmail: chair.email,
            responsibleSalesName: 'NA Person',
            responsibleSalesEmail: advisor.email,
          },
          status: 'new',
          existingGroupId: null,
          suggestedChairEmail: chair.email,
          suggestedNetworkAdvisorEmail: advisor.email,
        },
      ],
    })
    vi.stubGlobal('fetch', fetchMock)
    render(<ImportGroups />)

    fireEvent.click(screen.getByText('Add group'))
    fireEvent.change(screen.getByLabelText('EGN Group Name'), { target: { value: 'New Group' } })
    fireEvent.change(screen.getByLabelText('EGN Group Id'), { target: { value: '999' } })
    fireEvent.change(screen.getByLabelText('MMSGroup: Name'), { target: { value: 'MMS-1' } })
    fireEvent.change(screen.getByLabelText('Partner Code'), { target: { value: 'EGDK' } })
    fireEvent.change(screen.getByLabelText('Responsible Chair'), { target: { value: 'Chair Person' } })
    fireEvent.change(screen.getByLabelText('Responsible Chair Email'), { target: { value: chair.email } })
    fireEvent.change(screen.getByLabelText('Responsible Sales'), { target: { value: 'NA Person' } })
    fireEvent.change(screen.getByLabelText('Responsible Sales Email'), { target: { value: advisor.email } })
    fireEvent.click(screen.getByText('Check group'))

    await waitFor(() => {
      expect(screen.getByText('Review before import')).toBeInTheDocument()
    })
    expect(screen.getByText('New Group')).toBeInTheDocument()
    expect(screen.getByText('New')).toBeInTheDocument()
    // Best-guess Chair/NA should be pre-selected.
    expect(screen.getByLabelText('Chair for New Group')).toHaveValue(chair.email)
    expect(screen.getByLabelText('Network Advisor for New Group')).toHaveValue(advisor.email)

    fireEvent.click(screen.getByText('Confirm import'))

    await waitFor(() => {
      expect(fetchMock).toHaveBeenCalledWith(
        '/api/putGroups',
        expect.objectContaining({
          method: 'POST',
          body: expect.stringContaining('"egnGroupId":"999"'),
        }),
      )
    })
  })

  it('shows an unmatched Chair/NA email as "— unmatched —", not silently guessed or auto-created', async () => {
    const fetchMock = mockFetch({
      getUsers: [chair, advisor],
      checkGroupImport: [
        {
          row: {
            egnGroupName: 'New Group',
            egnGroupId: '999',
            mmsGroupCode: 'MMS-1',
            partnerCode: 'EGDK',
            groupProfile: '',
            memberProfile: '',
            companiesProfile: '',
            responsibleChairName: 'Someone Not Yet A User',
            responsibleChairEmail: 'not-a-user-yet@example.com',
            responsibleSalesName: 'NA Person',
            responsibleSalesEmail: advisor.email,
          },
          status: 'new',
          existingGroupId: null,
          // checkGroupImport itself found no matching User for this email —
          // this is what it returns in that case.
          suggestedChairEmail: null,
          suggestedNetworkAdvisorEmail: advisor.email,
        },
      ],
    })
    vi.stubGlobal('fetch', fetchMock)
    render(<ImportGroups />)

    fireEvent.click(screen.getByText('Add group'))
    fireEvent.change(screen.getByLabelText('EGN Group Name'), { target: { value: 'New Group' } })
    fireEvent.change(screen.getByLabelText('EGN Group Id'), { target: { value: '999' } })
    fireEvent.change(screen.getByLabelText('MMSGroup: Name'), { target: { value: 'MMS-1' } })
    fireEvent.change(screen.getByLabelText('Partner Code'), { target: { value: 'EGDK' } })
    fireEvent.change(screen.getByLabelText('Responsible Chair'), { target: { value: 'Someone Not Yet A User' } })
    fireEvent.change(screen.getByLabelText('Responsible Chair Email'), { target: { value: 'not-a-user-yet@example.com' } })
    fireEvent.change(screen.getByLabelText('Responsible Sales'), { target: { value: 'NA Person' } })
    fireEvent.change(screen.getByLabelText('Responsible Sales Email'), { target: { value: advisor.email } })
    fireEvent.click(screen.getByText('Check group'))

    await waitFor(() => {
      expect(screen.getByText('Review before import')).toBeInTheDocument()
    })
    expect(screen.getByLabelText('Chair for New Group')).toHaveValue('')
    expect(screen.getByLabelText('Network Advisor for New Group')).toHaveValue(advisor.email)
  })

  it('rejects a non-UTF-8 CSV file with a clear banner', async () => {
    vi.stubGlobal('fetch', mockFetch({}))
    render(<ImportGroups />)

    fireEvent.click(screen.getByText('Import CSV'))
    // 0xE6 alone is invalid UTF-8 (a lone continuation-expecting lead byte).
    const badBytes = new Uint8Array([0x68, 0x65, 0x6c, 0x6c, 0x6f, 0xe6])
    const file = new File([badBytes], 'groups.csv', { type: 'text/csv' })
    const input = screen.getByLabelText('CSV file')
    fireEvent.change(input, { target: { files: [file] } })

    await waitFor(() => {
      expect(screen.getByRole('alert')).toHaveTextContent('This file is not saved as UTF-8 — import blocked')
    })
  })

  it('rejects a CSV missing a required column, naming it', async () => {
    vi.stubGlobal('fetch', mockFetch({}))
    render(<ImportGroups />)

    fireEvent.click(screen.getByText('Import CSV'))
    const csv = [
      'EGN Group Name,EGN Group Id,MMSGroup: Name,Partner Code,Group Profile,Member Profile,Companies Profile,Responsible Sales',
      'Some Group,38494,02092-EGDK,EGDK,group text,member text,companies text,NA Person',
    ].join('\n')
    const file = new File([csv], 'groups.csv', { type: 'text/csv' })
    const input = screen.getByLabelText('CSV file')
    fireEvent.change(input, { target: { files: [file] } })

    await waitFor(() => {
      expect(screen.getByText('Missing required columns')).toBeInTheDocument()
    })
    expect(screen.getByText('Responsible Chair')).toBeInTheDocument()
    expect(screen.queryByText(/Check \d+ row/)).not.toBeInTheDocument()
  })

  it('does not block import when Responsible Chair/Sales Email columns are entirely absent — matched by name instead', async () => {
    vi.stubGlobal('fetch', mockFetch({}))
    render(<ImportGroups />)

    fireEvent.click(screen.getByText('Import CSV'))
    // Mirrors the real Salesforce export sample (prototypes/DK-Groups-export-UTF8-sample.csv),
    // which predates the email-matching columns added in commit bf9ef7a — missing both.
    const csv = [
      'EGN Group Name,EGN Group Id,MMSGroup: Name,Partner Code,Group Profile,Member Profile,Companies Profile,Responsible Chair,Responsible Sales',
      'Some Group,38494,02092-EGDK,EGDK,group text,member text,companies text,Chair Person,NA Person',
    ].join('\n')
    const file = new File([csv], 'groups.csv', { type: 'text/csv' })
    const input = screen.getByLabelText('CSV file')
    fireEvent.change(input, { target: { files: [file] } })

    await waitFor(() => {
      expect(screen.getByText('Check 1 row(s)')).toBeInTheDocument()
    })
    expect(screen.queryByText('Missing required columns')).not.toBeInTheDocument()
  })

  it('rejects individual CSV rows missing required metadata, keeping the valid rows checkable', async () => {
    vi.stubGlobal('fetch', mockFetch({}))
    render(<ImportGroups />)

    fireEvent.click(screen.getByText('Import CSV'))
    const csv = [
      'EGN Group Name,EGN Group Id,MMSGroup: Name,Partner Code,Group Profile,Member Profile,Companies Profile,Responsible Chair,Responsible Chair Email,Responsible Sales,Responsible Sales Email',
      'Good Group,38494,02092-EGDK,EGDK,group text,member text,companies text,Chair Person,chair@example.com,NA Person,na@example.com',
      'Bad Group,38495,02093-EGDK,EGDK,group text,member text,companies text,,chair@example.com,NA Person,na@example.com',
    ].join('\n')
    const file = new File([csv], 'groups.csv', { type: 'text/csv' })
    const input = screen.getByLabelText('CSV file')
    fireEvent.change(input, { target: { files: [file] } })

    await waitFor(() => {
      expect(screen.getByText('Rows that will be rejected (missing required fields)')).toBeInTheDocument()
    })
    expect(screen.getByText('Row 3 (Bad Group): missing Responsible Chair — will be rejected.')).toBeInTheDocument()
    // The good row survives and is still offered for checking.
    expect(screen.getByText('Check 1 row(s)')).toBeInTheDocument()
  })

  it('does not reject a row whose Responsible Chair/Sales Email cell is blank — matched by name instead', async () => {
    vi.stubGlobal('fetch', mockFetch({}))
    render(<ImportGroups />)

    fireEvent.click(screen.getByText('Import CSV'))
    const csv = [
      'EGN Group Name,EGN Group Id,MMSGroup: Name,Partner Code,Group Profile,Member Profile,Companies Profile,Responsible Chair,Responsible Chair Email,Responsible Sales,Responsible Sales Email',
      'Some Group,38494,02092-EGDK,EGDK,group text,member text,companies text,Chair Person,,NA Person,na@example.com',
    ].join('\n')
    const file = new File([csv], 'groups.csv', { type: 'text/csv' })
    const input = screen.getByLabelText('CSV file')
    fireEvent.change(input, { target: { files: [file] } })

    await waitFor(() => {
      expect(screen.getByText('Check 1 row(s)')).toBeInTheDocument()
    })
    expect(screen.queryByText('Rows that will be rejected (missing required fields)')).not.toBeInTheDocument()
  })

  it('flags a Chair/NA resolved by name fallback for verification, while still pre-selecting the match', async () => {
    const fetchMock = mockFetch({
      getUsers: [chair, advisor],
      checkGroupImport: [
        {
          row: {
            egnGroupName: 'New Group',
            egnGroupId: '999',
            mmsGroupCode: 'MMS-1',
            partnerCode: 'EGDK',
            groupProfile: '',
            memberProfile: '',
            companiesProfile: '',
            responsibleChairName: 'Chair Person',
            responsibleChairEmail: '',
            responsibleSalesName: 'NA Person',
            responsibleSalesEmail: advisor.email,
          },
          status: 'new',
          existingGroupId: null,
          suggestedChairEmail: chair.email,
          chairMatchedByName: true,
          suggestedNetworkAdvisorEmail: advisor.email,
          networkAdvisorMatchedByName: false,
        },
      ],
    })
    vi.stubGlobal('fetch', fetchMock)
    render(<ImportGroups />)

    fireEvent.click(screen.getByText('Add group'))
    fireEvent.change(screen.getByLabelText('EGN Group Name'), { target: { value: 'New Group' } })
    fireEvent.change(screen.getByLabelText('EGN Group Id'), { target: { value: '999' } })
    fireEvent.change(screen.getByLabelText('MMSGroup: Name'), { target: { value: 'MMS-1' } })
    fireEvent.change(screen.getByLabelText('Partner Code'), { target: { value: 'EGDK' } })
    fireEvent.change(screen.getByLabelText('Responsible Chair'), { target: { value: 'Chair Person' } })
    fireEvent.change(screen.getByLabelText('Responsible Sales'), { target: { value: 'NA Person' } })
    fireEvent.change(screen.getByLabelText('Responsible Sales Email'), { target: { value: advisor.email } })
    fireEvent.click(screen.getByText('Check group'))

    await waitFor(() => {
      expect(screen.getByText('Review before import')).toBeInTheDocument()
    })
    expect(screen.getByLabelText('Chair for New Group')).toHaveValue(chair.email)
    expect(screen.getByText('Matched by name — verify')).toBeInTheDocument()
  })

  it('shows the assigned Chair and Network Advisor by name on the groups list, and — when unassigned', async () => {
    const assignedGroup = { ...group, id: 'g2', name: 'Assigned Group', chairEmail: chair.email, networkAdvisorEmail: advisor.email }
    vi.stubGlobal('fetch', mockFetch({ getGroups: [group, assignedGroup], getUsers: [chair, advisor] }))
    render(<ImportGroups />)

    await waitFor(() => {
      expect(screen.getByText('Assigned Group')).toBeInTheDocument()
    })
    expect(screen.getByText('Chair Person')).toBeInTheDocument()
    expect(screen.getByText('NA Person')).toBeInTheDocument()
    // Test Group (chairEmail/networkAdvisorEmail both null) still renders '—' in those columns.
    expect(screen.getAllByText('—').length).toBeGreaterThan(0)
  })

  it('disables Score and Launch until a DNA version exists / an AI draft is pending', async () => {
    vi.stubGlobal('fetch', mockFetch({ getGroups: [group] }))
    render(<ImportGroups />)

    await waitFor(() => {
      expect(screen.getByText('Test Group')).toBeInTheDocument()
    })
    // '—' shows for the unassigned Chair/NA columns as well as the unset
    // Score column on this fixture (all three are null) — this test only
    // cares that Score itself renders as '—', not the exact count, so
    // assert presence rather than a single match.
    expect(screen.getAllByText('—').length).toBeGreaterThan(0)
    // Generate/Score/Launch are folded under one "Actions" button per row —
    // open it to reach the individual buttons. Scoped with `within` since
    // the Score *column* is also a sortable header button named "Score".
    fireEvent.click(screen.getByRole('button', { name: 'Actions' }))
    const menu = screen.getByRole('menu')
    expect(within(menu).getByRole('button', { name: 'Score' })).toBeDisabled()
    expect(within(menu).getByRole('button', { name: 'Launch' })).toBeDisabled()
  })

  it('runs the full Generate pipeline from the list row and refreshes the group afterwards', async () => {
    const generatedGroup = { ...group, latestDnaVersionId: 'v2', latestDnaVersionScore: 4, hasPendingAiDraft: true }
    const fetchMock = vi.fn(async (url: string) => {
      if (url === '/api/getUsers') return { ok: true, status: 200, json: async () => [] }
      if (url === '/api/getGroups') return { ok: true, status: 200, json: async () => (fetchMock.mock.calls.filter((c) => c[0] === '/api/getGroups').length > 1 ? [generatedGroup] : [group]) }
      if (url === '/api/generateDnaStage1') return { ok: true, status: 200, json: async () => ({ stage1Text: 'stage1' }) }
      if (url === '/api/generateDnaStage2') return { ok: true, status: 200, json: async () => ({ stage2Text: 'stage2' }) }
      if (url === '/api/scoreDna') return { ok: true, status: 200, json: async () => ({ score: 4 }) }
      if (url === '/api/commitDnaGeneration') return { ok: true, status: 200, json: async () => ({ importedVersionId: 'v1', autoGeneratedVersionId: 'v2' }) }
      throw new Error(`Unexpected fetch: ${url}`)
    })
    vi.stubGlobal('fetch', fetchMock)
    render(<ImportGroups />)

    await waitFor(() => {
      expect(screen.getByText('Test Group')).toBeInTheDocument()
    })
    fireEvent.click(screen.getByRole('button', { name: 'Actions' }))
    fireEvent.click(screen.getByText('Generate'))

    await waitFor(() => {
      expect(fetchMock).toHaveBeenCalledWith('/api/generateDnaStage1', expect.objectContaining({ body: JSON.stringify({ groupId: 'g1' }) }))
      expect(fetchMock).toHaveBeenCalledWith('/api/generateDnaStage2', expect.objectContaining({ body: JSON.stringify({ groupId: 'g1', stage1Text: 'stage1' }) }))
      expect(fetchMock).toHaveBeenCalledWith('/api/scoreDna', expect.objectContaining({ body: JSON.stringify({ text: 'stage2' }) }))
      expect(fetchMock).toHaveBeenCalledWith(
        '/api/commitDnaGeneration',
        expect.objectContaining({ body: JSON.stringify({ groupId: 'g1', stage2Text: 'stage2', autoGeneratedScore: 4 }) }),
      )
    })
    await waitFor(() => {
      expect(screen.getByText('4/5')).toBeInTheDocument()
    })
  })

  it('includes a pasted roster in the detail view\'s Generate/Regenerate call, but not when left blank', async () => {
    const fetchMock = mockFetch({ getGroups: [group], getGroup: groupDetail })
    vi.stubGlobal('fetch', fetchMock)
    render(<ImportGroups />)

    await waitFor(() => expect(screen.getByText('Test Group')).toBeInTheDocument())
    fireEvent.click(screen.getByText('Test Group'))
    await waitFor(() => expect(screen.getByText('Regenerate')).toBeInTheDocument())

    fireEvent.change(screen.getByLabelText('Group roster — titles + companies (optional)'), {
      target: { value: 'CFO — Acme A/S\nHead of Operations — Northco ApS' },
    })
    fireEvent.click(screen.getByText('Regenerate'))

    await waitFor(() => {
      expect(fetchMock).toHaveBeenCalledWith(
        '/api/generateDnaStage2',
        expect.objectContaining({
          body: JSON.stringify({ groupId: 'g1', stage1Text: 'stage1', roster: 'CFO — Acme A/S\nHead of Operations — Northco ApS' }),
        }),
      )
    })
    // Generate also persists it — so it's still there next time even if
    // the admin never separately clicked "Save roster".
    expect(fetchMock).toHaveBeenCalledWith(
      '/api/saveGroupRoster',
      expect.objectContaining({ body: JSON.stringify({ groupId: 'g1', roster: 'CFO — Acme A/S\nHead of Operations — Northco ApS' }) }),
    )
  })

  it('pre-fills the roster box from the group\'s own persisted roster, and saves edits on click', async () => {
    const fetchMock = mockFetch({ getGroups: [group], getGroup: { ...groupDetail, roster: 'CFO — Acme A/S' } })
    vi.stubGlobal('fetch', fetchMock)
    render(<ImportGroups />)

    await waitFor(() => expect(screen.getByText('Test Group')).toBeInTheDocument())
    fireEvent.click(screen.getByText('Test Group'))

    await waitFor(() => {
      expect(screen.getByLabelText('Group roster — titles + companies (optional)')).toHaveValue('CFO — Acme A/S')
    })

    fireEvent.change(screen.getByLabelText('Group roster — titles + companies (optional)'), { target: { value: 'CFO — Acme A/S\nCOO — Beta ApS' } })
    fireEvent.click(screen.getByText('Save roster'))

    await waitFor(() => {
      expect(fetchMock).toHaveBeenCalledWith(
        '/api/saveGroupRoster',
        expect.objectContaining({ method: 'POST', body: JSON.stringify({ groupId: 'g1', roster: 'CFO — Acme A/S\nCOO — Beta ApS' }) }),
      )
    })
    await waitFor(() => {
      expect(screen.getByText('Saved')).toBeInTheDocument()
    })
  })

  it('sends no roster field at all when the roster box is left blank', async () => {
    const fetchMock = mockFetch({ getGroups: [group], getGroup: groupDetail })
    vi.stubGlobal('fetch', fetchMock)
    render(<ImportGroups />)

    await waitFor(() => expect(screen.getByText('Test Group')).toBeInTheDocument())
    fireEvent.click(screen.getByText('Test Group'))
    await waitFor(() => expect(screen.getByText('Regenerate')).toBeInTheDocument())

    fireEvent.click(screen.getByText('Regenerate'))

    await waitFor(() => {
      expect(fetchMock).toHaveBeenCalledWith('/api/generateDnaStage2', expect.objectContaining({ body: JSON.stringify({ groupId: 'g1', stage1Text: 'stage1' }) }))
    })
  })

  it('carries a roster pasted in "Add one group manually" over to that same group\'s own Generate box', async () => {
    const createdGroup = { ...group, id: 'g-new', egnGroupId: '999', name: 'New Group' }
    // Simulates the server already having the roster saved by the time the
    // detail view is opened — the real save call is asserted separately below.
    const createdDetail = { ...groupDetail, id: 'g-new', egnGroupId: '999', name: 'New Group', latestDnaVersion: null, roster: 'CFO — Acme A/S' }
    const fetchMock = vi.fn(async (url: string) => {
      if (url === '/api/getUsers') return { ok: true, status: 200, json: async () => [chair, advisor] }
      if (url === '/api/getGroups') {
        const priorCalls = fetchMock.mock.calls.filter((c) => c[0] === '/api/getGroups').length
        return { ok: true, status: 200, json: async () => (priorCalls > 1 ? [group, createdGroup] : [group]) }
      }
      if (url === '/api/checkGroupImport') {
        return {
          ok: true,
          status: 200,
          json: async () => [
            {
              row: {
                egnGroupName: 'New Group',
                egnGroupId: '999',
                mmsGroupCode: 'MMS-1',
                partnerCode: 'EGDK',
                groupProfile: '',
                memberProfile: '',
                companiesProfile: '',
                responsibleChairName: 'Chair Person',
                responsibleChairEmail: chair.email,
                responsibleSalesName: 'NA Person',
                responsibleSalesEmail: advisor.email,
              },
              status: 'new',
              existingGroupId: null,
              suggestedChairEmail: chair.email,
              suggestedNetworkAdvisorEmail: advisor.email,
              chairMatchedByName: false,
              networkAdvisorMatchedByName: false,
            },
          ],
        }
      }
      if (url === '/api/putGroups') return { ok: true, status: 200, json: async () => ({ created: ['g-new'], overwritten: [] }) }
      if (url === '/api/saveGroupRoster') return { ok: true, status: 200, json: async () => ({ groupId: 'g-new', roster: 'CFO — Acme A/S' }) }
      if (url.startsWith('/api/getGroup?groupId=g-new')) return { ok: true, status: 200, json: async () => createdDetail }
      if (url.startsWith('/api/getGroup?')) return { ok: true, status: 200, json: async () => groupDetail }
      throw new Error(`Unexpected fetch: ${url}`)
    })
    vi.stubGlobal('fetch', fetchMock)
    render(<ImportGroups />)

    await waitFor(() => expect(screen.getByText('Test Group')).toBeInTheDocument())
    fireEvent.click(screen.getByText('Add group'))
    fireEvent.change(screen.getByLabelText('EGN Group Name'), { target: { value: 'New Group' } })
    fireEvent.change(screen.getByLabelText('EGN Group Id'), { target: { value: '999' } })
    fireEvent.change(screen.getByLabelText('MMSGroup: Name'), { target: { value: 'MMS-1' } })
    fireEvent.change(screen.getByLabelText('Partner Code'), { target: { value: 'EGDK' } })
    fireEvent.change(screen.getByLabelText('Responsible Chair'), { target: { value: 'Chair Person' } })
    fireEvent.change(screen.getByLabelText('Responsible Chair Email'), { target: { value: chair.email } })
    fireEvent.change(screen.getByLabelText('Responsible Sales'), { target: { value: 'NA Person' } })
    fireEvent.change(screen.getByLabelText('Responsible Sales Email'), { target: { value: advisor.email } })
    fireEvent.change(screen.getByLabelText('Group roster — titles + companies (optional)'), { target: { value: 'CFO — Acme A/S' } })
    fireEvent.click(screen.getByText('Check group'))

    await waitFor(() => expect(screen.getByText('Review before import')).toBeInTheDocument())
    fireEvent.click(screen.getByText('Confirm import'))

    await waitFor(() => {
      expect(fetchMock).toHaveBeenCalledWith(
        '/api/saveGroupRoster',
        expect.objectContaining({ method: 'POST', body: JSON.stringify({ groupId: 'g-new', roster: 'CFO — Acme A/S' }) }),
      )
    })

    await waitFor(() => expect(screen.getByText('New Group')).toBeInTheDocument())
    fireEvent.click(screen.getByText('New Group'))

    await waitFor(() => {
      expect(screen.getByLabelText('Group roster — titles + companies (optional)')).toHaveValue('CFO — Acme A/S')
    })
  })

  it('labels a failed Generate step by stage, so a generic server error is still actionable', async () => {
    const fetchMock = vi.fn(async (url: string) => {
      if (url === '/api/getUsers') return { ok: true, status: 200, json: async () => [] }
      if (url === '/api/getGroups') return { ok: true, status: 200, json: async () => [group] }
      if (url === '/api/generateDnaStage1') return { ok: true, status: 200, json: async () => ({ stage1Text: 'stage1' }) }
      if (url === '/api/generateDnaStage2') {
        return { ok: false, status: 500, json: async () => ({ error: 'Something went wrong. Please try again.' }) }
      }
      throw new Error(`Unexpected fetch: ${url}`)
    })
    vi.stubGlobal('fetch', fetchMock)
    render(<ImportGroups />)

    await waitFor(() => {
      expect(screen.getByText('Test Group')).toBeInTheDocument()
    })
    fireEvent.click(screen.getByRole('button', { name: 'Actions' }))
    fireEvent.click(screen.getByText('Generate'))

    await waitFor(() => {
      expect(screen.getByText('Stage 2 failed (500): Something went wrong. Please try again.')).toBeInTheDocument()
    })
  })

  it('calls launchGroup when Launch is clicked on a group with a pending AI draft', async () => {
    const pendingGroup = { ...group, latestDnaVersionId: 'v2', latestDnaVersionScore: 4, hasPendingAiDraft: true }
    const fetchMock = mockFetch({ getGroups: [pendingGroup] })
    vi.stubGlobal('fetch', fetchMock)
    render(<ImportGroups />)

    await waitFor(() => {
      expect(screen.getByText('Test Group')).toBeInTheDocument()
    })
    fireEvent.click(screen.getByRole('button', { name: 'Actions' }))
    fireEvent.click(screen.getByText('Launch'))

    await waitFor(() => {
      expect(fetchMock).toHaveBeenCalledWith('/api/launchGroup', expect.objectContaining({ body: JSON.stringify({ groupId: 'g1' }) }))
    })
  })

  it('opens a group detail view showing the latest DNA version content, reachable from the list', async () => {
    vi.stubGlobal('fetch', mockFetch({ getGroups: [group] }))
    render(<ImportGroups />)

    await waitFor(() => {
      expect(screen.getByText('Test Group')).toBeInTheDocument()
    })
    fireEvent.click(screen.getByText('Test Group'))

    await waitFor(() => {
      expect(screen.getByText('v2, Ai')).toBeInTheDocument()
    })
    expect(screen.getByText('draft group profile')).toBeInTheDocument()
    expect(screen.getByText('4/5')).toBeInTheDocument()

    fireEvent.click(screen.getByText('← Back to groups'))
    await waitFor(() => {
      expect(screen.getByText('Groups')).toBeInTheDocument()
    })
  })

  it('renders the left-rail metadata and splits a templated profile into labelled fields', async () => {
    const templatedDetail = {
      ...groupDetail,
      chairEmail: chair.email,
      networkAdvisorEmail: advisor.email,
      latestDnaVersion: {
        ...groupDetail.latestDnaVersion,
        content: {
          groupProfile: 'GRUPPEPROFIL\n**Hvem er gruppen for**\nLedere med ansvar.\n\n**Udviklingsfokus**\n(ikke eksplicit defineret)',
          memberProfile: 'draft member profile',
          companiesProfile: 'draft companies profile',
        },
      },
    }
    vi.stubGlobal('fetch', mockFetch({ getGroups: [group], getUsers: [chair, advisor], getGroup: templatedDetail }))
    render(<ImportGroups />)

    await waitFor(() => {
      expect(screen.getByText('Test Group')).toBeInTheDocument()
    })
    fireEvent.click(screen.getByText('Test Group'))

    await waitFor(() => {
      expect(screen.getByText('Hvem er gruppen for')).toBeInTheDocument()
    })
    // The section header line ("GRUPPEPROFIL") is dropped — only the two labelled fields render.
    expect(screen.queryByText('GRUPPEPROFIL', { exact: false })).not.toBeInTheDocument()
    expect(screen.getByText('Ledere med ansvar.')).toBeInTheDocument()
    expect(screen.getByText('Udviklingsfokus')).toBeInTheDocument()
    expect(screen.getByText('(ikke eksplicit defineret)')).toBeInTheDocument()

    // Left rail: identity, status, IDs, Chair/NA.
    expect(screen.getByText('Draft generated')).toBeInTheDocument()
    expect(screen.getByText('38494')).toBeInTheDocument()
    expect(screen.getByText('02092-EGDK')).toBeInTheDocument()
    expect(screen.getByText(chair.name)).toBeInTheDocument()
    expect(screen.getByText(advisor.name)).toBeInTheDocument()
  })

  it('pre-fills the Chair/NA assignment selects from the group detail, offering every Chair/NA as options', async () => {
    const assignedDetail = { ...groupDetail, chairEmail: chair.email, networkAdvisorEmail: advisor.email }
    vi.stubGlobal('fetch', mockFetch({ getGroups: [group], getUsers: [chair, advisor], getGroup: assignedDetail }))
    render(<ImportGroups />)

    await waitFor(() => {
      expect(screen.getByText('Test Group')).toBeInTheDocument()
    })
    fireEvent.click(screen.getByText('Test Group'))

    await waitFor(() => {
      expect(screen.getByText('Reassign')).toBeInTheDocument()
    })
    fireEvent.click(screen.getByText('Reassign'))

    await waitFor(() => {
      expect(screen.getByLabelText('Chair')).toHaveValue(chair.email)
    })
    expect(screen.getByLabelText('Network Advisor')).toHaveValue(advisor.email)
    expect(screen.getByRole('option', { name: chair.name })).toBeInTheDocument()
    expect(screen.getByRole('option', { name: advisor.name })).toBeInTheDocument()
  })

  it('saves a Chair/NA reassignment and refreshes the group afterward', async () => {
    const fetchMock = mockFetch({
      getGroups: [group],
      getUsers: [chair, advisor],
      getGroup: groupDetail,
      reassignGroup: { status: 200, body: { groupId: 'g1', chairEmail: chair.email, networkAdvisorEmail: advisor.email } },
    })
    vi.stubGlobal('fetch', fetchMock)
    render(<ImportGroups />)

    await waitFor(() => {
      expect(screen.getByText('Test Group')).toBeInTheDocument()
    })
    fireEvent.click(screen.getByText('Test Group'))

    await waitFor(() => {
      expect(screen.getByText('Reassign')).toBeInTheDocument()
    })
    fireEvent.click(screen.getByText('Reassign'))

    await waitFor(() => {
      expect(screen.getByLabelText('Chair')).toBeInTheDocument()
    })
    fireEvent.change(screen.getByLabelText('Chair'), { target: { value: chair.email } })
    fireEvent.change(screen.getByLabelText('Network Advisor'), { target: { value: advisor.email } })
    fireEvent.click(screen.getByText('Save assignment'))

    await waitFor(() => {
      expect(fetchMock).toHaveBeenCalledWith(
        '/api/reassignGroup',
        expect.objectContaining({
          method: 'POST',
          body: JSON.stringify({ groupId: 'g1', chairEmail: chair.email, networkAdvisorEmail: advisor.email }),
        }),
      )
    })
    // refreshAfterAction re-fetches the group list.
    await waitFor(() => {
      expect(fetchMock.mock.calls.filter(([url]) => url === '/api/getGroups').length).toBe(2)
    })
  })

  it('shows an error when saving a Chair/NA reassignment fails', async () => {
    vi.stubGlobal(
      'fetch',
      mockFetch({
        getGroups: [group],
        getUsers: [chair, advisor],
        getGroup: groupDetail,
        reassignGroup: { status: 400, body: { error: 'na@example.com is not a User with the NetworkAdvisor role.' } },
      }),
    )
    render(<ImportGroups />)

    await waitFor(() => {
      expect(screen.getByText('Test Group')).toBeInTheDocument()
    })
    fireEvent.click(screen.getByText('Test Group'))

    await waitFor(() => {
      expect(screen.getByText('Reassign')).toBeInTheDocument()
    })
    fireEvent.click(screen.getByText('Reassign'))

    await waitFor(() => {
      expect(screen.getByLabelText('Chair')).toBeInTheDocument()
    })
    fireEvent.click(screen.getByText('Save assignment'))

    await waitFor(() => {
      expect(screen.getByRole('alert')).toHaveTextContent('na@example.com is not a User with the NetworkAdvisor role.')
    })
  })

  it('opens the Edit modal, pre-filled, from the list row Actions menu', async () => {
    vi.stubGlobal('fetch', mockFetch({ getGroups: [group], getGroup: groupDetail }))
    render(<ImportGroups />)

    await waitFor(() => {
      expect(screen.getByText('Test Group')).toBeInTheDocument()
    })
    fireEvent.click(screen.getByRole('button', { name: 'Actions' }))
    const menu = screen.getByRole('menu')
    fireEvent.click(within(menu).getByRole('button', { name: 'Edit' }))

    // Navigates to the detail view (same as clicking the group name) and
    // auto-opens the same Edit modal the detail view's own Edit button uses.
    await waitFor(() => {
      expect(screen.getByRole('heading', { name: 'Edit group' })).toBeInTheDocument()
    })
    expect(screen.getByLabelText('EGN Group Name')).toHaveValue('Test Group')
  })

  it('opens the Delete confirmation from the list row Actions menu', async () => {
    vi.stubGlobal('fetch', mockFetch({ getGroups: [group], getGroup: groupDetail }))
    render(<ImportGroups />)

    await waitFor(() => {
      expect(screen.getByText('Test Group')).toBeInTheDocument()
    })
    fireEvent.click(screen.getByRole('button', { name: 'Actions' }))
    const menu = screen.getByRole('menu')
    fireEvent.click(within(menu).getByRole('button', { name: 'Delete' }))

    await waitFor(() => {
      expect(screen.getByRole('heading', { name: 'Delete group' })).toBeInTheDocument()
    })
    expect(screen.getByText((_, el) => el?.tagName === 'STRONG' && el.textContent === 'Test Group')).toBeInTheDocument()
  })

  it('only shows "Reset to imported" when the group has an import snapshot, and lets an Admin discard edits back to it', async () => {
    const withSnapshot = {
      ...groupDetail,
      name: 'Edited Name',
      groupProfile: 'edited group profile',
      importedSnapshot: {
        egnGroupName: 'Test Group',
        mmsGroupCode: '02092-EGDK',
        partnerCode: 'EGDK',
        groupProfile: 'original group profile',
        memberProfile: 'original member profile',
        companiesProfile: 'original companies profile',
      },
    }
    const fetchMock = mockFetch({
      getGroups: [group],
      getGroup: withSnapshot,
      resetGroup: {
        status: 200,
        body: {
          groupId: 'g1',
          name: 'Test Group',
          mmsGroupCode: '02092-EGDK',
          partnerCode: 'EGDK',
          country: 'Denmark',
          groupProfile: 'original group profile',
          memberProfile: 'original member profile',
          companiesProfile: 'original companies profile',
          pendingReapproval: false,
        },
      },
    })
    vi.stubGlobal('fetch', fetchMock)
    render(<ImportGroups />)

    await waitFor(() => {
      expect(screen.getByText('Test Group')).toBeInTheDocument()
    })
    fireEvent.click(screen.getByText('Test Group'))

    await waitFor(() => {
      expect(screen.getByText('Reset to imported')).toBeInTheDocument()
    })
    fireEvent.click(screen.getByText('Reset to imported'))

    await waitFor(() => {
      expect(screen.getByRole('heading', { name: 'Reset to imported' })).toBeInTheDocument()
    })
    fireEvent.click(screen.getByRole('button', { name: 'Reset group' }))

    await waitFor(() => {
      expect(fetchMock).toHaveBeenCalledWith('/api/resetGroup', expect.objectContaining({ method: 'POST', body: JSON.stringify({ groupId: 'g1' }) }))
    })
  })

  it('does not show "Reset to imported" for a group with no import snapshot', async () => {
    vi.stubGlobal('fetch', mockFetch({ getGroups: [group], getGroup: groupDetail }))
    render(<ImportGroups />)

    await waitFor(() => {
      expect(screen.getByText('Test Group')).toBeInTheDocument()
    })
    fireEvent.click(screen.getByText('Test Group'))

    await waitFor(() => {
      expect(screen.getByText('v2, Ai')).toBeInTheDocument()
    })
    expect(screen.queryByText('Reset to imported')).not.toBeInTheDocument()
  })

  it('toggles the profile cards to the as-imported snapshot via the "Show original" tab', async () => {
    const withSnapshot = {
      ...groupDetail,
      importedSnapshot: {
        egnGroupName: 'Test Group',
        mmsGroupCode: '02092-EGDK',
        partnerCode: 'EGDK',
        groupProfile: 'original group profile',
        memberProfile: 'original member profile',
        companiesProfile: 'original companies profile',
      },
    }
    vi.stubGlobal('fetch', mockFetch({ getGroups: [group], getGroup: withSnapshot }))
    render(<ImportGroups />)

    await waitFor(() => {
      expect(screen.getByText('Test Group')).toBeInTheDocument()
    })
    fireEvent.click(screen.getByText('Test Group'))

    await waitFor(() => {
      // Current view shows the latest DnaVersion's draft content (same as the pre-existing behavior).
      expect(screen.getByText('draft group profile')).toBeInTheDocument()
    })
    fireEvent.click(screen.getByText('Show original'))

    await waitFor(() => {
      expect(screen.getByText('original group profile')).toBeInTheDocument()
    })
    expect(screen.queryByText('draft group profile')).not.toBeInTheDocument()

    fireEvent.click(screen.getByText('Current'))
    await waitFor(() => {
      expect(screen.getByText('draft group profile')).toBeInTheDocument()
    })
  })
})
