// Resolves what text Stage 1 (Notary) actually runs on for a given group:
// spec §10's Regenerate rule is "using the current approved text as
// input", which this reads as the group's latest existing DnaVersion if
// one exists (any stage — Imported/AutoGenerated/Chair-edited), falling
// back to the raw Group fields only for a true first-ever generation. One
// code path serves both "first generate" and "regenerate".
import { DnaContentSchema, type DnaContent } from '../../../shared/schemas/dna'
import { prisma } from '../auth'

export async function resolveGenerationInput(groupId: string): Promise<DnaContent | null> {
  const group = await prisma.group.findUnique({ where: { id: groupId } })
  if (!group) return null

  const latest = await prisma.dnaVersion.findFirst({ where: { groupId }, orderBy: { versionNumber: 'desc' } })
  if (latest) {
    const parsed = DnaContentSchema.safeParse(latest.content)
    if (parsed.success) return parsed.data
  }
  return { groupProfile: group.groupProfile, memberProfile: group.memberProfile, companiesProfile: group.companiesProfile }
}

/** Matches the prototype's /api/pipeline raw-input shape verbatim. */
export function buildRawInputText(content: DnaContent): string {
  return `GROUP PROFILE (raw):\n${content.groupProfile}\n\nMEMBER PROFILE (raw):\n${content.memberProfile}\n\nCOMPANIES PROFILE (raw):\n${content.companiesProfile}`
}
